-- ================================================================
-- 724BAHİS.NET — Sohbet Yönetim ve Moderasyon Sistemi Schema (Extended)
-- Supabase Dashboard > SQL Editor'de çalıştırın
-- ================================================================

-- 1. CHANNELS (Sohbet Kanalları) Tablosu (Extended)
CREATE TABLE IF NOT EXISTS chat_channels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    is_private BOOLEAN DEFAULT FALSE,
    category TEXT DEFAULT 'Genel',
    icon_url TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    order_index INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE chat_channels ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can read chat_channels" ON chat_channels;
DROP POLICY IF EXISTS "Service can manage chat_channels" ON chat_channels;
CREATE POLICY "Public can read chat_channels" ON chat_channels FOR SELECT USING (true);
CREATE POLICY "Service can manage chat_channels" ON chat_channels FOR ALL USING (true);

-- 2. BANS (Yasaklı Kullanıcılar) Tablosu (Extended)
CREATE TABLE IF NOT EXISTS chat_bans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT REFERENCES chat_channels(id) ON DELETE CASCADE,
    user_id UUID NOT NULL,
    username TEXT NOT NULL DEFAULT 'Bilinmeyen',
    ban_type TEXT DEFAULT 'mute' CHECK (ban_type IN ('mute','ban')),
    mute_until TIMESTAMP WITH TIME ZONE,
    reason TEXT,
    admin_id TEXT DEFAULT 'admin',
    admin_username TEXT DEFAULT 'Yönetici',
    is_active BOOLEAN DEFAULT TRUE,
    banned_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE chat_bans ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can read chat_bans" ON chat_bans;
DROP POLICY IF EXISTS "Service can manage chat_bans" ON chat_bans;
CREATE POLICY "Public can read chat_bans" ON chat_bans FOR SELECT USING (true);
CREATE POLICY "Service can manage chat_bans" ON chat_bans FOR ALL USING (true);

CREATE INDEX IF NOT EXISTS idx_chat_bans_user_id ON chat_bans(user_id);
CREATE INDEX IF NOT EXISTS idx_chat_bans_active ON chat_bans(is_active, mute_until);

-- 3. LOGS (Mesaj/Mesajlaşma Günlükleri) Tablosu
CREATE TABLE IF NOT EXISTS chat_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel_id BIGINT REFERENCES chat_channels(id) ON DELETE CASCADE,
    user_id UUID NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE chat_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can read chat_logs" ON chat_logs;
DROP POLICY IF EXISTS "Public can insert chat_logs" ON chat_logs;
DROP POLICY IF EXISTS "Service can manage chat_logs" ON chat_logs;
CREATE POLICY "Public can read chat_logs" ON chat_logs FOR SELECT USING (true);
CREATE POLICY "Public can insert chat_logs" ON chat_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Service can manage chat_logs" ON chat_logs FOR ALL USING (true);

-- 4. MODERATION LOGS (Moderasyon/Yönetici Logları) Tablosu
CREATE TABLE IF NOT EXISTS chat_moderation_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action TEXT NOT NULL,
    admin_id TEXT NOT NULL,
    admin_username TEXT NOT NULL,
    target_user_id TEXT,
    target_username TEXT,
    channel_id BIGINT,
    channel_name TEXT,
    details JSONB DEFAULT '{}',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

ALTER TABLE chat_moderation_logs ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can read chat_moderation_logs" ON chat_moderation_logs;
DROP POLICY IF EXISTS "Public can insert chat_moderation_logs" ON chat_moderation_logs;
DROP POLICY IF EXISTS "Service can manage chat_moderation_logs" ON chat_moderation_logs;
CREATE POLICY "Public can read chat_moderation_logs" ON chat_moderation_logs FOR SELECT USING (true);
CREATE POLICY "Public can insert chat_moderation_logs" ON chat_moderation_logs FOR INSERT WITH CHECK (true);
CREATE POLICY "Service can manage chat_moderation_logs" ON chat_moderation_logs FOR ALL USING (true);

CREATE INDEX IF NOT EXISTS idx_chat_mod_logs_created_at ON chat_moderation_logs(created_at DESC);

-- Enable Realtime
-- Note: Run these in DB if publication doesn't exist, otherwise handles gracefully
DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE chat_bans;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Publication table addition skipped or already exists';
END $$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE chat_moderation_logs;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Publication table addition skipped or already exists';
END $$;

DO $$
BEGIN
    ALTER PUBLICATION supabase_realtime ADD TABLE chat_channels;
EXCEPTION WHEN OTHERS THEN
    RAISE NOTICE 'Publication table addition skipped or already exists';
END $$;

-- Default settings in site_configs
INSERT INTO site_configs (key, value, updated_at) VALUES
  ('chat_settings', '{"chat_enabled": true, "rate_limit_seconds": 15, "max_message_length": 500}', NOW())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW();

-- Default channels
INSERT INTO chat_channels (name, slug, category, is_active, order_index) VALUES
  ('Genel Sohbet', 'genel-sohbet', 'Genel', true, 1),
  ('Maç Sohbeti', 'mac-sohbeti', 'Spor', true, 2),
  ('VIP Lounge', 'vip-lounge', 'VIP', true, 3)
ON CONFLICT (slug) DO NOTHING;
