import { Brand, MarqueeConfig, WelcomePopupConfig, LiveOddsConfig, WheelConfig, SiteStatusConfig, RaffleConfig, PopularBetsConfig, NewsSliderConfig, TVConfig, LoaderConfig, TrustedCompany } from './types';
import { demoPopularBets } from './demoData';

export const BRANDS: Brand[] = [
  {
    id: 'marsbahis',
    name: 'MARSBAHİS',
    subtitle: 'MARSBAHİS BANKASIDIR',
    offerMain: 'ANINDA',
    offerSub: '%10 NAKİT İADE',
    bonusText: 'DENEME BONUSU',
    logo: 'https://picsum.photos/seed/mars/200/200',
    link: '#',
  },
  {
    id: 'stake',
    name: 'STAKE',
    subtitle: 'CASINO & SPORTS...',
    offerMain: 'GÜVEN',
    offerSub: 'OYNA KAZAN',
    bonusText: 'DENEME BONUSU',
    logo: 'https://picsum.photos/seed/stake/200/200',
    link: '#',
  },
  {
    id: 'misty',
    name: 'MİSTY CASİNO',
    subtitle: 'KAZANMANIN YERİ',
    offerMain: '100',
    offerSub: 'FREE SPIN',
    bonusText: 'DENEME BONUSU',
    logo: 'https://picsum.photos/seed/misty/200/200',
    link: '#',
  },
  {
    id: 'casitoros',
    name: 'CASİTOROS',
    subtitle: 'CASINO & SPORTS...',
    offerMain: '%10',
    offerSub: 'KRİPTO ARTIŞI',
    bonusText: 'DENEME BONUSU',
    logo: 'https://picsum.photos/seed/toros/200/200',
    link: '#',
  },
  {
    id: 'casitap',
    name: 'CASİTAP',
    subtitle: 'CASINO & SPORTS...',
    offerMain: '1000',
    offerSub: 'TL DENEME BONUSU',
    bonusText: 'DENEME BONUSU',
    logo: 'https://picsum.photos/seed/tap/200/200',
    link: '#',
  },
];

export const DEFAULT_MARQUEE_CONFIG: MarqueeConfig = {
  isActive: true,
  text: 'Hoş geldiniz! En yüksek oranlar ve anında ödeme 724BETS güvencesiyle!',
  speed: 60,
  color: '#FFC107', // 724BETS Yellow
  isBold: true,
};

export const DEFAULT_WELCOME_POPUP_CONFIG: WelcomePopupConfig = {
  isActive: true,
  title: '724BETS',
  subtitle: "Türkiye'nin En Dinamik ve Güvenilir Bahis Platformu",
  offerMain: '%200 HOŞGELDİN BONUSU',
  offerSub: 'İlk yatırımınıza özel · Anında hesabınıza yüklenir',
  buttonText: '🚀 HEMEN KAYDOL — ÜCRETSİZ',
  buttonLink: 'https://bahisbey1438.com/?btag=59649488_330539',
};

export const DEFAULT_LIVE_ODDS_CONFIG: LiveOddsConfig = {
  isActive: true,
  speed: 10,
  matches: [],
};

export const DEFAULT_WHEEL_CONFIG: WheelConfig = {
  rewards: [
    { id: '1', label: '100 TL Nakit', color: '#f0b90b', weight: 1, type: 'nakit', value: '100' },
    { id: '2', label: '50 Free Spin', color: '#1a1a1a', weight: 2, type: 'freespin', value: '50' },
    { id: '3', label: '200 TL Bonus', color: '#f0b90b', weight: 1, type: 'bonus', value: '200' },
    { id: '4', label: 'Pas Geç', color: '#1a1a1a', weight: 3, type: 'pas', value: '0' },
    { id: '5', label: '10 TL Teselli', color: '#f0b90b', weight: 4, type: 'nakit', value: '10' },
  ],
  lastSpinTime: 0,
  spinCooldownHours: 6,
};

export const DEFAULT_SITE_STATUS_CONFIG: SiteStatusConfig = {
    isMaintenanceMode: false,
    maintenanceMessage: 'Değerli üyelerimiz, sistemlerimizde planlı bir bakım çalışması yürütülmektedir. Çok kısa bir süre sonra tekrar sizinle olacağız!',
};

export const DEFAULT_LOADER_CONFIG: LoaderConfig = {
    isActive: true,
};

export const DEFAULT_RAFFLE_CONFIG: RaffleConfig = {
    drawDate: '2024-04-20T21:00:00',
    isActive: true,
    prizes: [
        { id: '1', rank: '1.', prize: 'iPhone 17 Pro Max', emoji: '📱', color: '#f0b90b' },
        { id: '2', rank: '2.', prize: '5,000 TL Nakit', emoji: '💵', color: '#10b981' },
        { id: '3', rank: '3.', prize: '1,000 TL Bonus', emoji: '🎁', color: '#8b5cf6' },
        { id: '4', rank: '4-10.', prize: '250 TL Freespin', emoji: '🎰', color: '#f59e0b' },
    ],
    rules: [
        { icon: 'Shield', text: 'Her kullanıcı en fazla 10 bilet satın alabilir.' },
        { icon: 'AlertTriangle', text: 'Bilet satın alımı geri iade edilemez.' },
        { icon: 'CheckCircle', text: 'Her 500 TL yatırım = 1 Bilet hakkı kazandırır.' },
        { icon: 'Users', text: 'Çekiliş sonuçları şeffaf algoritma ile belirlenir.' },
        { icon: 'Trophy', text: 'Kazananlar çekiliş gününde canlı olarak açıklanır.' },
        { icon: 'Info', text: 'Bilet havuzundaki slot numaranız çekilişte kullanılır.' },
    ],
    faqs: [
        { q: "Bilet nasıl kazanılır?", a: "Sponsor sitemiz 724BETS'e yatırımlar yaparak veya Görevler sekmesindeki etkinlikleri tamamlayarak bilet kazanabilirsiniz." },
        { q: "Bilet talebi nasıl oluşturulur?", a: "Görevler sayfasındaki form aracılığıyla 724BETS kullanıcı adınızı, yatırım miktarınızı ve tarihini girerek talep oluşturabilirsiniz." },
        { q: "Yatırım tarihi ve saati neden isteniyor?", a: "Yatırımınızın sistem tarafından teyit edilebilmesi için talep edilmektedir." },
        { q: "Bilet talebim ne kadar sürede onaylanır?", a: "Talepleriniz uzman ekibimiz tarafından kontrol edilip en kısa sürede otomatik olarak onaylanır." },
        { q: "Bilet liderliği nasıl çalışır?", a: "Bilet havuzumuzdan, en fazla bilete sahip olan kullanıcıların biletleri sıralı olarak sergilenir." },
        { q: "Çekiliş nasıl yapılır?", a: "Çekiliş günlerinde bilet havuzundaki biletler arasından şeffaf bir bilgisayar algoritması ile kazananlar belirlenir." },
        { q: "Sponsor bilgisi neden isteniyor?", a: "Çekilişlerimiz partnerimiz 724BETS sponsorluğunda gerçekleştiği için oyuncu teyiti zorunludur." },
        { q: "Telefon doğrulaması neden gerekli?", a: "Sadece gerçek kişilerin ödül alabilmesi ve multi hesapların engellenmesi için istenmektedir." }
    ]
};

export const DEFAULT_POPULAR_BETS_CONFIG: PopularBetsConfig = {
    isActive: true,
    bets: demoPopularBets
};

export const DEFAULT_NEWS_SLIDER_CONFIG: NewsSliderConfig = {
    isActive: true,
    autoPlayInterval: 5000,
    slides: [
        {
            id: 'ns-1',
            imageUrl: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?q=80&w=2070&auto=format&fit=crop',
            link: '#',
            title: 'Real Madrid - Manchester City Maçı Öncesi Son Dakika Gelişmeleri',
            category: 'ŞAMPİYONLAR LİGİ',
            isActive: true,
            order: 1
        },
        {
            id: 'ns-2',
            imageUrl: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=2093&auto=format&fit=crop',
            link: '#',
            title: 'Süper Lig\'de Şampiyonluk Yarışında Kritik Haftaya Girildi',
            category: 'SÜPER LİG',
            isActive: true,
            order: 2
        },
        {
            id: 'ns-3',
            imageUrl: 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?q=80&w=2069&auto=format&fit=crop',
            link: '#',
            title: 'Euro 2024 Öncesi A Milli Takım\'da Hazırlıklar Tam Gaz Sürüyor',
            category: 'A MİLLİ TAKIM',
            isActive: true,
            order: 3
        }
    ]
};

import { BettingMatch } from './types';

export const DEFAULT_BETTING_MATCHES: BettingMatch[] = [
    {
        id: 'bm-1',
        league: 'EURO 2024',
        homeTeam: 'Portekiz',
        awayTeam: 'İspanya',
        matchTime: '06/07 22:00',
        odds: { home: '4.03', draw: '3.57', away: '1.95' },
        isActive: true
    },
    {
        id: 'bm-2',
        league: 'EURO 2024',
        homeTeam: 'Amerika Birleşik Devletleri',
        awayTeam: 'Belçika',
        matchTime: '07/07 03:00',
        odds: { home: '2.50', draw: '3.41', away: '2.87' },
        isActive: true
    },
    {
        id: 'bm-3',
        league: 'EURO 2024',
        homeTeam: 'Arjantin',
        awayTeam: 'Mısır',
        matchTime: '07/07 19:00',
        odds: { home: '1.38', draw: '4.79', away: '9.30' },
        isActive: true
    },
    {
        id: 'bm-4',
        league: 'EURO 2024',
        homeTeam: 'İsviçre',
        awayTeam: 'Kolombiya',
        matchTime: '07/07 23:00',
        odds: { home: '3.57', draw: '3.09', away: '2.28' },
        isActive: true
    },
    {
        id: 'bm-5',
        league: 'EURO 2024',
        homeTeam: 'Fransa',
        awayTeam: 'Fas',
        matchTime: '09/07 23:00',
        odds: { home: '1.61', draw: '3.90', away: '6.10' },
        isActive: true
    },
    {
        id: 'bm-6',
        league: 'EURO 2024',
        homeTeam: 'Norveç',
        awayTeam: 'İngiltere',
        matchTime: '12/07 00:00',
        odds: { home: '4.02', draw: '3.70', away: '1.91' },
        isActive: true
    }
];

export const DEFAULT_TV_CONFIG: TVConfig = {
    isActive: true,
    chatEnabled: true,
    tickerText: '724BAHİS.NET | EN YÜKSEK ORANLAR - ANINDA ÇEKİM | TÜM MAÇLAR CANLI VE KESİNTİSİZ | HOŞGELDİN BONUSUNUZU ALMAYI UNUTMAYIN!',
    channels: [
        {
            id: "ch-bein1",
            name: "7/24 BEIN SPORTS 1",
            slug: "bein-sports-1",
            tags: ["beIN SPORTS"],
            isVip: false,
            order: 1,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=zirve",
            streamUrl: "bein-sports-1",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/bein1.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "bein-sports-1",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-bein2",
            name: "7/24 BEIN SPORTS 2",
            slug: "bein-sports-2",
            tags: ["beIN SPORTS"],
            isVip: false,
            order: 2,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=b2",
            streamUrl: "bein-sports-2",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/bein2.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "bein-sports-2",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-bein3",
            name: "7/24 BEIN SPORTS 3",
            slug: "bein-sports-3",
            tags: ["beIN SPORTS"],
            isVip: false,
            order: 3,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=b3",
            streamUrl: "bein-sports-3",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/bein3.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "bein-sports-3",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-bein4",
            name: "7/24 BEIN SPORTS 4",
            slug: "bein-sports-4",
            tags: ["beIN SPORTS"],
            isVip: false,
            order: 4,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=b4",
            streamUrl: "bein-sports-4",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/bein4.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "bein-sports-4",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-bein5",
            name: "7/24 BEIN SPORTS 5",
            slug: "bein-sports-5",
            tags: ["beIN SPORTS"],
            isVip: false,
            order: 5,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=b5",
            streamUrl: "bein-sports-5",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/bein5.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "bein-sports-5",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-beinmax1",
            name: "7/24 BEIN SPORTS MAX 1",
            slug: "bein-sports-max-1",
            tags: ["beIN SPORTS"],
            isVip: false,
            order: 6,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=bm1",
            streamUrl: "bein-sports-max-1",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/beinmax1.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "bein-sports-max-1",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-beinmax2",
            name: "7/24 BEIN SPORTS MAX 2",
            slug: "bein-sports-max-2",
            tags: ["beIN SPORTS"],
            isVip: false,
            order: 7,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=bm2",
            streamUrl: "bein-sports-max-2",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/beinmax2.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "bein-sports-max-2",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-ssport",
            name: "7/24 S SPORT",
            slug: "s-sport",
            tags: ["S SPORT"],
            isVip: false,
            order: 8,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=ss",
            streamUrl: "s-sport",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/ssport.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "s-sport",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-ssport2",
            name: "7/24 S SPORT 2",
            slug: "s-sport-2",
            tags: ["S SPORT"],
            isVip: false,
            order: 9,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=ss2",
            streamUrl: "s-sport-2",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/ssport2.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "s-sport-2",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-smartspor",
            name: "7/24 SMART SPOR",
            slug: "smart-spor",
            tags: ["SMART SPOR"],
            isVip: false,
            order: 10,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=smarts",
            streamUrl: "smart-spor",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/smartspor.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "smart-spor",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-smartspor2",
            name: "7/24 SMART SPOR 2",
            slug: "smart-spor-2",
            tags: ["SMART SPOR"],
            isVip: false,
            order: 11,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=sms2",
            streamUrl: "smart-spor-2",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/smartspor2.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "smart-spor-2",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-tivibu1",
            name: "7/24 TIVIBU SPOR 1",
            slug: "tivibu-spor-1",
            tags: ["TIVIBU SPOR"],
            isVip: false,
            order: 12,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=t1",
            streamUrl: "tivibu-spor-1",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/tivibu1.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "tivibu-spor-1",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-tivibu2",
            name: "7/24 TIVIBU SPOR 2",
            slug: "tivibu-spor-2",
            tags: ["TIVIBU SPOR"],
            isVip: false,
            order: 13,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=t2",
            streamUrl: "tivibu-spor-2",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/tivibu2.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "tivibu-spor-2",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-tivibu3",
            name: "7/24 TIVIBU SPOR 3",
            slug: "tivibu-spor-3",
            tags: ["TIVIBU SPOR"],
            isVip: false,
            order: 14,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=t3",
            streamUrl: "tivibu-spor-3",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/tivibu3.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "tivibu-spor-3",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-tivibu4",
            name: "7/24 TIVIBU SPOR 4",
            slug: "tivibu-spor-4",
            tags: ["TIVIBU SPOR"],
            isVip: false,
            order: 15,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=t4",
            streamUrl: "tivibu-spor-4",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/tivibu4.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "tivibu-spor-4",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-trtspor",
            name: "7/24 TRT SPOR",
            slug: "trt-spor",
            tags: ["TRT"],
            isVip: false,
            order: 16,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=trtspor",
            streamUrl: "trt-spor",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/trtspor.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "trt-spor",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-trtsporyildiz",
            name: "7/24 TRT SPOR YILDIZ",
            slug: "trt-spor-yildiz",
            tags: ["TRT"],
            isVip: false,
            order: 17,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=trtspor2",
            streamUrl: "trt-spor-yildiz",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/trtspor2.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "trt-spor-yildiz",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-aspor",
            name: "7/24 A SPOR",
            slug: "a-spor",
            tags: ["Ulusal"],
            isVip: false,
            order: 18,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=as",
            streamUrl: "a-spor",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/aspor.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "a-spor",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-euro1",
            name: "7/24 EURO SPORT 1",
            slug: "euro-sport-1",
            tags: ["DİĞER"],
            isVip: false,
            order: 19,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=eu1",
            streamUrl: "euro-sport-1",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/euro1.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "euro-sport-1",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-euro2",
            name: "7/24 EURO SPORT 2",
            slug: "euro-sport-2",
            tags: ["DİĞER"],
            isVip: false,
            order: 20,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=eu2",
            streamUrl: "euro-sport-2",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/euro2.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "euro-sport-2",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-tabii",
            name: "7/24 TABII SPOR",
            slug: "tabii-spor",
            tags: ["TABİİ"],
            isVip: false,
            order: 21,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=ex7",
            streamUrl: "tabii-spor",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/tabii.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "tabii-spor",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-tabii1",
            name: "7/24 TABII SPOR 1",
            slug: "tabii-spor-1",
            tags: ["TABİİ"],
            isVip: false,
            order: 22,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=ex1",
            streamUrl: "tabii-spor-1",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/tabii.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "tabii-spor-1",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-tabii2",
            name: "7/24 TABII SPOR 2",
            slug: "tabii-spor-2",
            tags: ["TABİİ"],
            isVip: false,
            order: 23,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=ex2",
            streamUrl: "tabii-spor-2",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/tabii.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "tabii-spor-2",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-tabii3",
            name: "7/24 TABII SPOR 3",
            slug: "tabii-spor-3",
            tags: ["TABİİ"],
            isVip: false,
            order: 24,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=ex3",
            streamUrl: "tabii-spor-3",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/tabii.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "tabii-spor-3",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-tabii4",
            name: "7/24 TABII SPOR 4",
            slug: "tabii-spor-4",
            tags: ["TABİİ"],
            isVip: false,
            order: 25,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=ex4",
            streamUrl: "tabii-spor-4",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/tabii.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "tabii-spor-4",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-tabii5",
            name: "7/24 TABII SPOR 5",
            slug: "tabii-spor-5",
            tags: ["TABİİ"],
            isVip: false,
            order: 26,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=ex5",
            streamUrl: "tabii-spor-5",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/tabii.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "tabii-spor-5",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-tabii6",
            name: "7/24 TABII SPOR 6",
            slug: "tabii-spor-6",
            tags: ["TABİİ"],
            isVip: false,
            order: 27,
            isLive: true,
            category: "🏆 SPOR KANALLARI",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=ex6",
            streamUrl: "tabii-spor-6",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/tabii.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "tabii-spor-6",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-trt1",
            name: "7/24 TRT 1",
            slug: "trt-1",
            tags: ["TRT"],
            isVip: false,
            order: 28,
            isLive: true,
            category: "📺 ULUSAL KANALLAR",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=trt1",
            streamUrl: "trt-1",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/trt1.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "trt-1",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-atv",
            name: "7/24 ATV",
            slug: "atv",
            tags: ["Ulusal"],
            isVip: false,
            order: 29,
            isLive: true,
            category: "📺 ULUSAL KANALLAR",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=atv",
            streamUrl: "atv",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/atv.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "atv",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-tv8",
            name: "7/24 TV 8",
            slug: "tv-8",
            tags: ["Ulusal"],
            isVip: false,
            order: 30,
            isLive: true,
            category: "📺 ULUSAL KANALLAR",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=tv8",
            streamUrl: "tv-8",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/tv8.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "tv-8",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        },
        {
            id: "ch-tv85",
            name: "7/24 TV 8,5",
            slug: "tv-8-5",
            tags: ["Ulusal"],
            isVip: false,
            order: 31,
            isLive: true,
            category: "📺 ULUSAL KANALLAR",
            isActive: true,
            platform: "iframe" as any,
            videoUrl: "",
            iframeUrl: "https://xslotlive2.xyz/channel?id=tv85",
            streamUrl: "tv-8-5",
            sourceType: "iframe",
            platformType: "iframe" as any,
            thumbnailUrl: "https://tipobettv264.com/img/tv85.png",
            viewerCount: 0,
            fallbackType: "none",
            platformUsername: "tv-8-5",
            fallbackVideoUrl: "",
            fallbackIframeUrl: ""
        }
    ]
};

// ─── Güvenilir Siteler — Seed Data ───────────────────────────────────────────
// nextCommentAt and createdAt/lastUpdated are filled by trustedEngine.ts on seed.

export const TRUSTED_COMPANIES_SEED: Omit<TrustedCompany, 'nextCommentAt' | 'createdAt' | 'lastUpdated'>[] = [
  {
    id: 'diamondbet',
    name: 'BetLivo',
    logo: '/promos/betlivo-logo.png',
    affiliateLink: '#',
    tier: 'featured',
    overallScore: 10.0,
    safetyScore: 10.0,
    bonusScore: 9.8,
    supportScore: 9.9,
    paymentScore: 9.7,
    welcomeBonus: '%200 Çevrimsiz + 1000 FS',
    bonusDetail: '%40 Nakit İade',
    features: ['Tüm Kripto Paralar', 'Sınırsız Çekim', 'VIP Hizmet', '7/24 Destek', 'Lisanslı'],
    pros: [
      'Çevrimsiz hoşgeldin bonusu ile anında nakit',
      '15 dakikadan kısa çekim süreleri',
      'Tüm kripto para birimleri desteklenir',
      'Özel VIP müşteri hattı',
      'Curacao ve Malta çift lisanslı',
      'Canlı casino streaming kalitesi üstün',
      'Spor bahislerinde piyasanın en yüksek oranları',
    ],
    cons: [
      'Yeni hesaplarda kimlik doğrulama zorunlu',
    ],
    description: 'DiamondBet, Türk bahis piyasasının tartışmasız zirvesi. 2018\'den bu yana kesintisiz hizmet veren platform, özellikle çevrimsiz bonus politikası ve ultra hızlı çekim süreleriyle sektörde devrim yarattı. Malta Gaming Authority ve Curacao eGaming tarafından çift lisanslı olan DiamondBet, her yatırımın güvencede olduğunun garantisini verir. VIP programı, yüksek hacimli oyuncular için özel cashback, kişisel hesap yöneticisi ve öncelikli çekim işleme gibi ayrıcalıklar sunar.',
    licenseInfo: 'Curacao eGaming #5536/JAZ · MGA/CRP/2018',
    foundedYear: 2018,
    minDeposit: '50 TL',
    withdrawalSpeed: '15 Dakika',
    isActive: true,
    isFeatured: true,
    order: 1,
    commentDripEnabled: true,
  },
  {
    id: 'grandbet',
    name: 'GrandBet',
    logo: 'https://picsum.photos/seed/grandbet/200/200',
    affiliateLink: '#',
    tier: 'gold',
    overallScore: 9.8,
    safetyScore: 9.5,
    bonusScore: 9.8,
    supportScore: 9.3,
    paymentScore: 9.4,
    welcomeBonus: '%100 Çevrimsiz',
    bonusDetail: '%30 Anlık Kayıp İadesi',
    features: ['Kripto', 'Havale', 'Lisanslı & Onaylı'],
    pros: [
      '%100 Çevrimsiz hoşgeldin bonusu',
      'Anlık kayıp iadesi her gün',
      'Geniş spor bahis marketi',
      'Hızlı Papara ödemeleri',
      'Güçlü mobil uygulama',
    ],
    cons: [
      'Slot bölümü rakiplerine kıyasla biraz dar',
      'Hafta sonu destek yanıt süresi uzayabiliyor',
    ],
    description: 'GrandBet, 2019 yılında kurulan ve kısa sürede Türk oyunculara güvenilir bir liman haline gelen platform. Özellikle %100 çevrimsiz hoşgeldin bonusu ve günlük kayıp iadesi sistemi ile öne çıkıyor. Spor bahislerinde 1000\'den fazla market sunan GrandBet, futbol tutkunu oyuncular için ideal seçim.',
    licenseInfo: 'Curacao eGaming #8048/JAZ2019',
    foundedYear: 2019,
    minDeposit: '100 TL',
    withdrawalSpeed: '1-2 Saat',
    isActive: true,
    isFeatured: false,
    order: 2,
    commentDripEnabled: true,
  },
  {
    id: 'elitecasino',
    name: 'EliteCasino',
    logo: 'https://picsum.photos/seed/elitecasino/200/200',
    affiliateLink: '#',
    tier: 'gold',
    overallScore: 9.8,
    safetyScore: 9.6,
    bonusScore: 9.9,
    supportScore: 9.2,
    paymentScore: 9.5,
    welcomeBonus: '5000 TL Bonus',
    bonusDetail: '250 FreeSpin',
    features: ['Papara', 'Tether', 'VIP Ayrıcalıkları', 'Yeni'],
    pros: [
      '5000 TL\'ye kadar hoşgeldin paketi',
      '250 freespin ilk yatırımda',
      'Pragmatic Play ve Evolution Gaming lisanslı',
      'Haftalık reload bonusları',
      'Tether (USDT) anlık işlem desteği',
    ],
    cons: [
      'Spor bahis bölümü casino kadar güçlü değil',
      'Belge doğrulama 24 saat sürebiliyor',
    ],
    description: 'EliteCasino, casino tutkunlarına özel tasarlanmış premium bir platform. Slot ve canlı casino kategorilerinde sektörün en güçlü sağlayıcılarıyla çalışan EliteCasino, 5000 TL\'ye kadar ulaşan hoşgeldin paketi ve 250 freespin ile rakiplerinden sıyrılıyor. Özellikle live casino deneyimi, gerçek krupiyeler eşliğinde üst düzey bir atmosfer sunuyor.',
    licenseInfo: 'Curacao eGaming #365/JAZ2020',
    foundedYear: 2020,
    minDeposit: '150 TL',
    withdrawalSpeed: '2-4 Saat',
    isActive: true,
    isFeatured: false,
    order: 3,
    commentDripEnabled: true,
  },
  {
    id: 'trustbet',
    name: 'TrustBet',
    logo: 'https://picsum.photos/seed/trustbet/200/200',
    affiliateLink: '#',
    tier: 'silver',
    overallScore: 9.2,
    safetyScore: 9.0,
    bonusScore: 8.8,
    supportScore: 9.1,
    paymentScore: 9.0,
    welcomeBonus: '%20 Çevrimsiz Yatırım',
    bonusDetail: '7/24 Kesintisiz Müşteri Desteği',
    features: ['Güvenilir Altyapı', 'Anlık Papara'],
    pros: [
      'Hat çekim garantisi',
      '7/24 kesintisiz müşteri desteği',
      'Deneyimli ve onaylı platform',
      'Hızlı Papara işlemleri',
    ],
    cons: [
      'Bonus oranları öncü rakiplerine göre daha düşük',
      'Casino oyun sayısı sınırlı',
    ],
    description: 'TrustBet, ismini hak eden bir platform. Müşteri memnuniyetini her şeyin önünde tutan TrustBet, özellikle 7/24 canlı destek kalitesi ve güvenilir ödeme altyapısıyla öne çıkıyor.',
    licenseInfo: 'Curacao eGaming #5536/JAZ',
    foundedYear: 2020,
    minDeposit: '100 TL',
    withdrawalSpeed: '3-6 Saat',
    isActive: true,
    isFeatured: false,
    order: 4,
    commentDripEnabled: true,
  },
  {
    id: 'progaming',
    name: 'ProGaming',
    logo: 'https://picsum.photos/seed/progaming/200/200',
    affiliateLink: '#',
    tier: 'silver',
    overallScore: 9.0,
    safetyScore: 8.8,
    bonusScore: 9.2,
    supportScore: 8.9,
    paymentScore: 8.7,
    welcomeBonus: '100 TL Deneme Bonusu',
    bonusDetail: 'Geniş Bahis Seçenekleri',
    features: ['Yüksek Oranlar', 'Güvenilir'],
    pros: [
      'Geniş bahis seçenekleri',
      'Yüksek oranlar ile dikkat çekici platform',
      'Deneme bonusu ile risksiz başlangıç',
    ],
    cons: [
      'Ödeme yöntemleri çeşitliliği artırılabilir',
      'Mobil uygulama daha akıcı olabilir',
    ],
    description: 'ProGaming, geniş spor bahis marketi ve rekabetçi oranlarıyla spor severler için güçlü bir seçim. 100 TL deneme bonusuyla yeni üyelere risksiz bir başlangıç imkânı sunuyor.',
    licenseInfo: 'Curacao eGaming #8048/JAZ',
    foundedYear: 2021,
    minDeposit: '100 TL',
    withdrawalSpeed: '4-8 Saat',
    isActive: true,
    isFeatured: false,
    order: 5,
    commentDripEnabled: true,
  },
  {
    id: 'safeplay',
    name: 'SafePlay',
    logo: 'https://picsum.photos/seed/safeplay/200/200',
    affiliateLink: '#',
    tier: 'silver',
    overallScore: 8.5,
    safetyScore: 9.5,
    bonusScore: 8.0,
    supportScore: 8.5,
    paymentScore: 8.8,
    welcomeBonus: '%25 Kayıp İadesi',
    bonusDetail: 'Her Gün Yenilenen Promosyonlar',
    features: ['Denetlenmiş Site', 'Güvenli Ödeme'],
    pros: [
      'Güvenlik odaklı altyapı',
      'Her gün yenilenen promosyonlar',
      'Anında ödeme güvencesi',
    ],
    cons: [
      'Bonus miktarları rakiplerine göre mütevazı',
      'Oyun çeşitliliği genişletilebilir',
    ],
    description: 'SafePlay, isminin tam karşılığını veren bir platform. Güvenli ödeme altyapısı ve sıkı denetim standartlarıyla hassas oyuncular için güvenli bir tercih.',
    licenseInfo: 'Curacao eGaming #5536/JAZ',
    foundedYear: 2021,
    minDeposit: '50 TL',
    withdrawalSpeed: '6-12 Saat',
    isActive: true,
    isFeatured: false,
    order: 6,
    commentDripEnabled: true,
  },
  {
    id: 'bronzebet',
    name: 'BronzeBet',
    logo: 'https://picsum.photos/seed/bronzebet/200/200',
    affiliateLink: '#',
    tier: 'bronze',
    overallScore: 8.2,
    safetyScore: 8.0,
    bonusScore: 7.8,
    supportScore: 8.0,
    paymentScore: 8.0,
    welcomeBonus: '%50 Hoşgeldin',
    bonusDetail: 'Standart Bonus Paketi',
    features: ['Temel Bahis'],
    pros: ['Basit ve kullanıcı dostu arayüz', 'Temel bahis ihtiyaçlarını karşılıyor'],
    cons: ['Premium özellikler eksik', 'Bonus çevrim şartları yüksek'],
    description: 'BronzeBet, temel bahis ihtiyaçlarını karşılayan düzgün bir platform. Büyük iddialar taşımasa da güvenilir ödeme ve standart hizmet sunar.',
    licenseInfo: 'Curacao eGaming #365/JAZ',
    foundedYear: 2022,
    minDeposit: '100 TL',
    withdrawalSpeed: '12-24 Saat',
    isActive: true,
    isFeatured: false,
    order: 7,
    commentDripEnabled: true,
  },
  {
    id: 'starterwin',
    name: 'StarterWin',
    logo: 'https://picsum.photos/seed/starterwin/200/200',
    affiliateLink: '#',
    tier: 'bronze',
    overallScore: 7.8,
    safetyScore: 7.5,
    bonusScore: 8.0,
    supportScore: 7.8,
    paymentScore: 7.5,
    welcomeBonus: '%75 İlk Yatırım',
    bonusDetail: 'Yeni Başlayanlar İçin',
    features: ['Başlangıç Bonusu'],
    pros: ['Yeni başlayanlar için uygun', 'Düşük minimum yatırım'],
    cons: ['Sınırlı oyun seçeneği', 'VIP program yok'],
    description: 'StarterWin, bahise yeni başlayanlar için tasarlanmış sade ve anlaşılır bir platform. Düşük minimum yatırım ve başlangıç bonusuyla yeni üyeler için cazip.',
    licenseInfo: 'Curacao eGaming #365/JAZ',
    foundedYear: 2023,
    minDeposit: '50 TL',
    withdrawalSpeed: '24-48 Saat',
    isActive: true,
    isFeatured: false,
    order: 8,
    commentDripEnabled: true,
  },
];
