import { MatchAnalysis, NewsArticle } from './types';

export const demoAnalyses: MatchAnalysis[] = [
    // MARCH 31 - NATIONAL MATCHES
    {
        id: 'kosovo-turkey-20260331',
        league: 'Milli Maçlar',
        homeTeam: 'KOSOVA',
        awayTeam: 'TÜRKİYE',
        matchTime: '21:45',
        matchDate: '2026-03-31',
        analysis: 'Maç Analizi: Ay-yıldızlı ekibimiz, yarı finalde Romanya engelini aşarak finale yükseldi. Kosova ise sürpriz bir çıkışla Slovakya’yı eledi. Priştine’de ateşli bir atmosfer bizi beklese de, kadro kalitesi ve tecrübe anlamında net favoriyiz. Arda Güler ve Kenan Yıldız\'ın yaratıcılığı, Kosova\'nın savunma boşluklarını cezalandıracaktır. Günün Tercihi: Maç Sonucu 2 (Türkiye Kazanır). Sürpriz Tercih: Karşılıklı Gol Var & MS 2. Skor Tahmini: 1-2.',
        tacticalSummary: 'Arda Güler ve Kenan Yıldız\'ın yaratıcılığı belirleyici olacaktır.',
        breakingPoint: 'Savunma boşluklarının cezalandırılması.',
        bettingScenario: 'Milli heyecan en yüksek oranlarla 724BAHİS iş ortaklığıyla sitemizde!',
        prediction: 'MS 2 (TÜRKİYE KAZANIR)',
        confidence: 94,
        modelScore: 89,
        recentHistory: 'Yeni Analiz',
        expectedGoals: '2.50',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.92', odd2: '2.05', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.85', odd2: '1.98', link: 'https://google.com' }
        ],
        createdAt: Date.now()
    },
    {
        id: 'sweden-poland-20260331',
        league: 'Milli Maçlar',
        homeTeam: 'İSVEÇ',
        awayTeam: 'POLONYA',
        matchTime: '21:45',
        matchDate: '2026-03-31',
        analysis: 'Maç Analizi: Gecenin en sert eşleşmesi. İsveç’te formunun zirvesinde olan Gyökeres, Polonya savunması için en büyük tehdit. Polonya ise Lewandowski sonrası dönemde daha kolektif bir oyun sergiliyor ancak deplasmanda olmaları büyük dezavantaj. Fizik gücü yüksek, düşük tempolu bir maç bekliyoruz. Günün Tercihi: 2.5 Alt. Sürpriz Tercih: Maç Sonucu 0 (Beraberlik - Uzatmalara Gider). Skor Tahmini: 1-1.',
        tacticalSummary: 'Gyökeres tehdidi ve fizik gücü yüksek oyun.',
        breakingPoint: 'Polonya\'nın deplasman dezavantajı.',
        bettingScenario: 'Bu maçın canlı bahis seçenekleri maç saatinde 724bets.net\'te yayında olacak.',
        prediction: '2.5 ALT',
        confidence: 88,
        modelScore: 85,
        recentHistory: 'Yeni Analiz',
        expectedGoals: '1.95',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.85', odd2: '1.95', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.78', odd2: '1.88', link: 'https://google.com' }
        ],
        createdAt: Date.now()
    },
    {
        id: 'bosnia-italy-20260331',
        league: 'Milli Maçlar',
        homeTeam: 'BOSNA HERSEK',
        awayTeam: 'İTALYA',
        matchTime: '21:45',
        matchDate: '2026-03-31',
        analysis: 'Maç Analizi: İtalya, son dönemdeki formsuzluğunu bu finalle unutturmak istiyor. Bosna Hersek ise sahasında çok dirençli bir takım ancak İtalya\'nın orta saha üstünlüğü maçın kaderini belirleyecektir. İtalya kontrollü başlayıp ikinci yarıda sonuca gitmeye çalışacaktır. Günün Tercihi: Maç Sonucu 2 (İtalya Kazanır). Sürpriz Tercih: Toplam Gol Aralığı 2-3. Skor Tahmini: 0-2.',
        tacticalSummary: 'İtalya\'nın orta saha üstünlüğü belirleyici olacaktır.',
        breakingPoint: 'İkinci yarıda İtalya\'nın kuracağı baskı.',
        bettingScenario: 'İtalya\'nın katı savunmasına güvenenler için "Gök Mavililer Gol Yemez" seçeneği 724BAHİS\'da değerlendirilebilir.',
        prediction: 'MS 2 (İTALYA KAZANIR)',
        confidence: 90,
        modelScore: 87,
        recentHistory: 'Yeni Analiz',
        expectedGoals: '2.10',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.75', odd2: '1.85', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.70', odd2: '1.80', link: 'https://google.com' }
        ],
        createdAt: Date.now()
    },
    {
        id: 'czechia-denmark-20260331',
        league: 'Milli Maçlar',
        homeTeam: 'ÇEKYA',
        awayTeam: 'DANİMARKA',
        matchTime: '21:45',
        matchDate: '2026-03-31',
        analysis: 'Maç Analizi: İki disiplinli Avrupa ekibi karşı karşıya. Danimarka, yarı finaldeki 4-0\'lık galibiyetiyle ne kadar formda olduğunu gösterdi. Çekya ise daha çok duran toplar ve savunma disipliniyle ayakta kalmaya çalışıyor. Danimarka\'nın hücum zenginliği bu maçta ağır basıyor. Günün Tercihi: Danimarka Çifte Şans (02). Sürpriz Tercih: Maç Sonucu 2. Skor Tahmini: 0-1.',
        tacticalSummary: 'Danimarka\'nın hücum zenginliği ve disiplinli oyun.',
        breakingPoint: 'Danimarka\'nın yarı finaldeki 4-0\'lık performansı.',
        bettingScenario: 'Günün en dengeli maçı için "Sistem" kuponlarını tercih etmenizi öneriyoruz.',
        prediction: 'DANİMARKA ÇİFTE ŞANS (02)',
        confidence: 85,
        modelScore: 83,
        recentHistory: 'Yeni Analiz',
        expectedGoals: '2.25',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.68', odd2: '1.78', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.60', odd2: '1.70', link: 'https://google.com' }
        ],
        createdAt: Date.now()
    },
    // FEBRUARY 27
    {
        id: 'wolverhampton-villa',
        league: 'Premier League',
        homeTeam: 'WOLVERHAMPTON',
        awayTeam: 'ASTON VILLA',
        matchTime: '18:00',
        matchDate: '2026-02-27',
        analysis: '',
        tacticalSummary: 'Premier League temposu yüksek bir Midlands derbisi. Aston Villa topa daha fazla sahip olmayı hedeflerken, Wolverhampton geçiş oyununda etkili olmaya çalışacaktır. Villa’nın hücum hattı üretken ancak savunma arkasında boşluk bırakabiliyor. Wolves iç sahada agresif başlar.',
        breakingPoint: 'İlk 25 dakika. Villa öne geçerse maç açılır. Wolves erken gol bulursa oyun tamamen karşılıklı hücuma döner.',
        bettingScenario: 'İki takımda skor üretmeye yatkın. Erken gol gelirse 3.5 üst barajı bile zorlanabilir. 0-0 giderken tempo yüksekse canlı 2.5 Üst değerlendirilebilir.',
        prediction: 'KG VAR / 2.5 ÜST',
        confidence: 82,
        modelScore: 88,
        recentHistory: '7 Kazanç',
        expectedGoals: '2.85',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.72', odd2: '1.85', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.78', odd2: '1.92', link: 'https://google.com', isHighest: true }
        ],
        createdAt: 1772175957104
    },
    {
        id: 'augsburg-koln',
        league: 'Bundesliga',
        homeTeam: 'AUGSBURG',
        awayTeam: 'KÖLN',
        matchTime: '16:30',
        matchDate: '2026-02-27',
        analysis: '',
        tacticalSummary: 'Bundesliga’da alt sıraları ilgilendiren dengeli bir mücadele. Augsburg iç sahada kontrollü, Köln ise deplasmanda savunma güvenliğini ön planda tutuyor. Risk seviyesi düşük bir oyun bekleniyor.',
        breakingPoint: 'İlk golü atan taraf skoru korumaya oynayacaktır. 60. dakikaya kadar dengeli giderse tempo düşebilir.',
        bettingScenario: 'Orta saha mücadelesi yüksek, pozisyon sayısı sınırlı bir maç. 2.5 Alt ana senaryo. 0-0 devre ihtimali değerlendirilebilir.',
        prediction: '2.5 ALT',
        confidence: 76,
        modelScore: 82,
        recentHistory: '6 Kazanç',
        expectedGoals: '1.95',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.85', odd2: '1.95', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.92', odd2: '2.05', link: 'https://google.com', isHighest: true }
        ],
        createdAt: 1772175957104
    },
    {
        id: 'parma-cagliari',
        league: 'Serie A',
        homeTeam: 'PARMA',
        awayTeam: 'CAGLIARI',
        matchTime: '19:00',
        matchDate: '2026-02-27',
        analysis: '',
        tacticalSummary: 'Serie A’da taktik disiplin ön planda. Parma evinde kontrollü, Cagliari deplasmanda kapanan yapıda. Oyun sıkışık orta saha mücadelesine dönebilir.',
        breakingPoint: 'İlk gol çok belirleyici olacak. Özellikle 55-70 arası oyuncu değişiklikleri tempoyu belirler.',
        bettingScenario: 'Düşük tempolu, az gollü senaryo ağır basıyor. Parma kaybetmez seçeneği güvenli duruyor.',
        prediction: '2.5 ALT / 1X',
        confidence: 79,
        modelScore: 85,
        recentHistory: '9 Kazanç',
        expectedGoals: '2.10',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.65', odd2: '1.75', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.72', odd2: '1.82', link: 'https://google.com', isHighest: true }
        ],
        createdAt: 1772175957104
    },
    {
        id: 'levante-alaves',
        league: 'La Liga 2',
        homeTeam: 'LEVANTE',
        awayTeam: 'ALAVÉS',
        matchTime: '21:00',
        matchDate: '2026-02-27',
        analysis: '',
        tacticalSummary: 'İki ekip de savunmada kırılgan. Levante iç sahada baskılı oynarken Alavés kontra ataklarla etkili olabilir.',
        breakingPoint: 'İlk yarı son bölümü (30-45 dk). Bu aralıkta gol çıkma ihtimali yüksek.',
        bettingScenario: 'Karşılıklı gol olasılığı yüksek. Erken gol gelirse 2.5 Üst desteklenebilir.',
        prediction: 'KG VAR',
        confidence: 80,
        modelScore: 84,
        recentHistory: '7 Kazanç',
        expectedGoals: '2.40',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.75', odd2: '1.85', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.82', odd2: '1.92', link: 'https://google.com', isHighest: true }
        ],
        createdAt: 1772175957104
    },
    {
        id: 'strasbourg-lens',
        league: 'Ligue 1',
        homeTeam: 'STRASBOURG',
        awayTeam: 'LENS',
        matchTime: '22:00',
        matchDate: '2026-02-27',
        analysis: '',
        tacticalSummary: 'Lens tempolu ve önde basan bir ekip. Strasbourg iç sahada açık oyun oynuyor. Geçiş hücumları belirleyici olabilir.',
        breakingPoint: 'İlk 20 dakikada gol gelirse maç tamamen açılır.',
        bettingScenario: 'Yüksek tempo, bol pozisyon beklentisi. 2.5 Üst ön planda.',
        prediction: '2.5 ÜST',
        confidence: 84,
        modelScore: 89,
        recentHistory: '8 Kazanç',
        expectedGoals: '2.90',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.90', odd2: '2.00', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.98', odd2: '2.10', link: 'https://google.com', isHighest: true }
        ],
        createdAt: 1772175957104
    },
    {
        id: 'trabzon-karagumruk',
        league: 'Süper Lig',
        homeTeam: 'TRABZONSPOR',
        awayTeam: 'FATİH KARAGÜMRÜK',
        matchTime: '20:00',
        matchDate: '2026-02-27',
        analysis: '',
        tacticalSummary: 'Trabzonspor iç sahada baskılı başlar. Karagümrük açık oynarsa savunma arkası boşluklar oluşur.',
        breakingPoint: 'İlk gol Trabzon’dan gelirse fark açılabilir.',
        bettingScenario: 'Ev sahibi baskısı ve hücum gücü nedeniyle 2.5 Üst destekli galibiyet senaryosu güçlü.',
        prediction: 'TRABZONSPOR & 2.5 ÜST',
        confidence: 86,
        modelScore: 91,
        recentHistory: '10 Kazanç',
        expectedGoals: '3.15',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.10', odd2: '2.25', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '2.18', odd2: '2.35', link: 'https://google.com', isHighest: true }
        ],
        createdAt: 1772175957104
    },
    {
        id: 'basaksehir-konya',
        league: 'Süper Lig',
        homeTeam: 'BAŞAKŞEHİR',
        awayTeam: 'KONYASPOR',
        matchTime: '17:00',
        matchDate: '2026-02-27',
        analysis: '',
        tacticalSummary: 'Kontrollü ve taktik savaşı şeklinde geçmesi beklenen bir maç. Başakşehir set hücumunda zorlanabilir.',
        breakingPoint: 'Orta saha hakimiyeti maçın kaderini belirler.',
        bettingScenario: 'Risk düşük, tempo sınırlı. Alt senaryosu öne çıkıyor.',
        prediction: '2.5 ALT',
        confidence: 74,
        modelScore: 78,
        recentHistory: '5 Kazanç',
        expectedGoals: '1.80',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.68', odd2: '1.78', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.75', odd2: '1.85', link: 'https://google.com', isHighest: true }
        ],
        createdAt: 1772175957104
    },
    {
        id: 'porto-arouca',
        league: 'Liga Portugal',
        homeTeam: 'FC PORTO',
        awayTeam: 'AROUCA',
        matchTime: '21:30',
        matchDate: '2026-02-27',
        analysis: '',
        tacticalSummary: 'Porto iç sahada baskılı ve erken gol arayan bir ekip. Arouca savunmada zorlanabilir.',
        breakingPoint: 'Erken bir Porto golü direnci tamamen kıracaktır.',
        bettingScenario: 'Porto’nun domine edeceği bir maç. Handikaplı galibiyet ana hedef.',
        prediction: 'PORTO -1.5 H',
        confidence: 88,
        modelScore: 94,
        recentHistory: '9 Kazanç',
        expectedGoals: '3.40',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.55', odd2: '1.65', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.62', odd2: '1.72', link: 'https://google.com', isHighest: true }
        ],
        createdAt: 1772175957104
    },
    {
        id: 'sporting-estoril',
        league: 'Liga Portugal',
        homeTeam: 'SPORTING CP',
        awayTeam: 'ESTORIL',
        matchTime: '19:45',
        matchDate: '2026-02-27',
        analysis: '',
        tacticalSummary: 'Sporting tempolu başlar. Estoril savunması geçişlerde sorun yaşayabilir.',
        breakingPoint: 'İlk 15 dakikadaki baskı sonucu belirleyici olur.',
        bettingScenario: 'Erken gol gelirse fark büyüyebilir. Üst tercihi mantıklı.',
        prediction: '2.5 ÜST',
        confidence: 83,
        modelScore: 89,
        recentHistory: '8 Kazanç',
        expectedGoals: '3.10',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.45', odd2: '1.55', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.52', odd2: '1.62', link: 'https://google.com', isHighest: true }
        ],
        createdAt: 1772175957104
    },
    {
        id: 'telstar-breda',
        league: 'Eerste Divisie',
        homeTeam: 'TELSTAR',
        awayTeam: 'NAC BREDA',
        matchTime: '21:00',
        matchDate: '2026-02-27',
        analysis: '',
        tacticalSummary: 'Eredivisie/Eerste tempolu ve gollü yapısıyla bilinir. Telstar iç sahada agresif.',
        breakingPoint: 'Hücum değişimleri ve kanat akınları.',
        bettingScenario: 'Karşılıklı gol ve üst senaryosu güçlü. Bol pozisyonlu maç.',
        prediction: '2.5 ÜST',
        confidence: 81,
        modelScore: 86,
        recentHistory: '7 Kazanç',
        expectedGoals: '3.25',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.70', odd2: '1.80', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.78', odd2: '1.88', link: 'https://google.com', isHighest: true }
        ],
        createdAt: 1772175957104
    },

    // FEBRUARY 28
    {
        id: 'manutd-newcastle',
        league: 'Premier League',
        homeTeam: 'MANCHESTER UNITED',
        awayTeam: 'NEWCASTLE',
        matchTime: '17:00',
        matchDate: '2026-02-28',
        analysis: '',
        tacticalSummary: 'United iç sahada baskılı başlasa da savunma geçişlerinde açık veriyor. Newcastle fizik gücü yüksek ve kontra atakta etkili. Orta saha temposu yüksek bir mücadele bekleniyor.',
        breakingPoint: 'İlk 30 dakika. Erken gol gelirse tempo artar ve karşılıklı oyun oluşur.',
        bettingScenario: 'İki takım da skor üretmeye yatkın. 1-1 senaryosu güçlü. 2.5 Üst ana tercih.',
        prediction: 'KG VAR / 2.5 ÜST',
        confidence: 84,
        modelScore: 87,
        recentHistory: '6 Kazanç',
        expectedGoals: '2.95',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.68', odd2: '1.75', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.75', odd2: '1.85', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    },
    {
        id: 'bayern-mainz',
        league: 'Bundesliga',
        homeTeam: 'BAYERN MÜNİH',
        awayTeam: 'MAİNZ',
        matchTime: '16:30',
        matchDate: '2026-02-28',
        analysis: '',
        tacticalSummary: 'Bayern iç sahada dominant oyun oynar. Mainz savunma hattı baskı altında hata yapabiliyor.',
        breakingPoint: 'İlk gol erken gelirse fark büyüyebilir.',
        bettingScenario: 'Bayern’in tempolu ve çok pozisyonlu oyunu nedeniyle gollü senaryo ağır basıyor.',
        prediction: 'BAYERN -1.5 H / 3.5 ÜST',
        confidence: 89,
        modelScore: 95,
        recentHistory: '8 Kazanç',
        expectedGoals: '3.80',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.45', odd2: '2.10', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.52', odd2: '2.25', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    },
    {
        id: 'inter-torino',
        league: 'Serie A',
        homeTeam: 'INTER',
        awayTeam: 'TORINO',
        matchTime: '21:45',
        matchDate: '2026-02-28',
        analysis: '',
        tacticalSummary: 'Inter topa sahip olarak sabırlı oynar. Torino savunma ağırlıklı yapıdadır.',
        breakingPoint: 'Inter ilk golü bulursa tempo düşer.',
        bettingScenario: 'Kontrollü galibiyet senaryosu. 2-0 / 1-0 skor olasılığı yüksek.',
        prediction: 'INTER KAZANIR & 2.5 ALT',
        confidence: 83,
        modelScore: 88,
        recentHistory: '9 Kazanç',
        expectedGoals: '1.85',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.60', odd2: '1.70', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.68', odd2: '1.78', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    },
    {
        id: 'sociedad-sevilla',
        league: 'La Liga',
        homeTeam: 'REAL SOCIEDAD',
        awayTeam: 'SEVILLA',
        matchTime: '19:30',
        matchDate: '2026-02-28',
        analysis: '',
        tacticalSummary: 'La Liga’da taktik disiplin ön planda. Dengeli ve az gollü bir mücadele bekleniyor.',
        breakingPoint: 'Savunma hataları ve duran toplar.',
        bettingScenario: 'Düşük tempolu maç beklentisi. 2.5 Alt ana senaryo.',
        prediction: '2.5 ALT',
        confidence: 78,
        modelScore: 82,
        recentHistory: '5 Kazanç',
        expectedGoals: '1.70',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.75', odd2: '1.65', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.82', odd2: '1.72', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    },
    {
        id: 'psg-lille',
        league: 'Ligue 1',
        homeTeam: 'PSG',
        awayTeam: 'LILLE',
        matchTime: '22:00',
        matchDate: '2026-02-28',
        analysis: '',
        tacticalSummary: 'PSG iç sahada tempolu ve hücum ağırlıklı. Lille kontra tehdidi yaratabilir.',
        breakingPoint: 'Mbappe ve Dembele hızı.',
        bettingScenario: 'Tempolu maç. PSG galibiyeti ve üst barajı.',
        prediction: '2.5 ÜST / PSG KAZANIR',
        confidence: 87,
        modelScore: 92,
        recentHistory: '8 Kazanç',
        expectedGoals: '3.10',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.55', odd2: '1.65', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.62', odd2: '1.72', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    },
    {
        id: 'benfica-braga',
        league: 'Liga Portugal',
        homeTeam: 'BENFICA',
        awayTeam: 'BRAGA',
        matchTime: '21:00',
        matchDate: '2026-02-28',
        analysis: '',
        tacticalSummary: 'İki ekip de hücum gücü yüksek. Açık futbol bekleniyor.',
        breakingPoint: 'Hücum hattındaki bireysel yetenekler.',
        bettingScenario: 'Karşılıklı gol senaryosu güçlü.',
        prediction: 'KG VAR',
        confidence: 82,
        modelScore: 86,
        recentHistory: '7 Kazanç',
        expectedGoals: '2.80',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.70', odd2: '1.80', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.78', odd2: '1.88', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    },
    {
        id: 'flamengo-mineiro',
        league: 'Serie A (BRA)',
        homeTeam: 'FLAMENGO',
        awayTeam: 'ATLÉTICO MINEIRO',
        matchTime: '23:00',
        matchDate: '2026-02-28',
        analysis: '',
        tacticalSummary: 'Brezilya ligi tempolu başlar. Flamengo evinde baskılı, Mineiro kontra tehditli.',
        breakingPoint: 'İlk yarıdaki yüksek baskı.',
        bettingScenario: 'Karşılıklı gol olasılığı yüksek.',
        prediction: 'KG VAR',
        confidence: 80,
        modelScore: 84,
        recentHistory: '7 Kazanç',
        expectedGoals: '2.60',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.80', odd2: '1.90', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.88', odd2: '1.98', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    },
    {
        id: 'river-rosario',
        league: 'Liga Profesional',
        homeTeam: 'RIVER PLATE',
        awayTeam: 'ROSARIO CENTRAL',
        matchTime: '02:00',
        matchDate: '2026-02-28',
        analysis: '',
        tacticalSummary: 'River iç sahada kontrollü kazanma eğiliminde.',
        breakingPoint: 'Savunma disiplini.',
        bettingScenario: 'River galibiyeti ve az gollü maç.',
        prediction: 'RIVER KAZANIR & 2.5 ALT',
        confidence: 85,
        modelScore: 89,
        recentHistory: '9 Kazanç',
        expectedGoals: '1.90',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.50', odd2: '1.60', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.58', odd2: '1.68', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    },

    // MARCH 1
    {
        id: 'arsenal-tottenham',
        league: 'Premier League',
        homeTeam: 'ARSENAL',
        awayTeam: 'TOTTENHAM',
        matchTime: '16:30',
        matchDate: '2026-03-01',
        analysis: '',
        tacticalSummary: 'Londra derbisi yüksek tempolu geçer. İki takım da hücum gücü yüksek.',
        breakingPoint: 'İlk yarı son 15 dakika.',
        bettingScenario: 'Karşılıklı gol olasılığı yüksek. Erken gol çıkarsa 3.5 Üst denenebilir.',
        prediction: 'KG VAR / 2.5 ÜST',
        confidence: 86,
        modelScore: 91,
        recentHistory: '8 Kazanç',
        expectedGoals: '3.20',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.65', odd2: '1.75', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.72', odd2: '1.85', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    },
    {
        id: 'barca-valencia',
        league: 'La Liga',
        homeTeam: 'BARCELONA',
        awayTeam: 'VALENCIA',
        matchTime: '21:00',
        matchDate: '2026-03-01',
        analysis: '',
        tacticalSummary: 'Barcelona iç sahada baskılı ve topa sahip. Valencia savunmada kırılgan.',
        breakingPoint: 'Lamine Yamal ve Lewandowski etkinliği.',
        bettingScenario: 'Barcelona iç sahada baskılı ve topa sahip. Valencia savunmada kırılgan.',
        prediction: 'BARCELONA KAZANIR & 2.5 ÜST',
        confidence: 84,
        modelScore: 89,
        recentHistory: '7 Kazanç',
        expectedGoals: '3.00',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.45', odd2: '1.85', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.52', odd2: '1.95', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    },
    {
        id: 'juve-atalanta',
        league: 'Serie A',
        homeTeam: 'JUVENTUS',
        awayTeam: 'ATALANTA',
        matchTime: '19:00',
        matchDate: '2026-03-01',
        analysis: '',
        tacticalSummary: 'Atalanta tempolu, Juventus kontrollü ama skor buluyor.',
        breakingPoint: 'Orta saha presi.',
        bettingScenario: 'Atalanta tempolu, Juventus kontrollü ama skor buluyor.',
        prediction: 'KG VAR',
        confidence: 81,
        modelScore: 85,
        recentHistory: '6 Kazanç',
        expectedGoals: '2.45',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.75', odd2: '1.85', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.82', odd2: '1.92', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    },
    {
        id: 'dortmund-leipzig',
        league: 'Bundesliga',
        homeTeam: 'BORUSSIA DORTMUND',
        awayTeam: 'RB LEIPZIG',
        matchTime: '18:30',
        matchDate: '2026-03-01',
        analysis: '',
        tacticalSummary: 'Geçiş oyunları ve yüksek tempo bekleniyor.',
        breakingPoint: 'Savunma arkası koşular.',
        bettingScenario: 'Geçiş oyunları ve yüksek tempo bekleniyor.',
        prediction: '2.5 ÜST',
        confidence: 85,
        modelScore: 90,
        recentHistory: '9 Kazanç',
        expectedGoals: '3.30',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.60', odd2: '1.70', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.68', odd2: '1.78', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    },
    {
        id: 'marseille-monaco',
        league: 'Ligue 1',
        homeTeam: 'MARSEILLE',
        awayTeam: 'MONACO',
        matchTime: '22:00',
        matchDate: '2026-03-01',
        analysis: '',
        tacticalSummary: 'İki ekip de hücum kalitesi yüksek.',
        breakingPoint: 'Kanat hücumları.',
        bettingScenario: 'İki ekip de hücum kalitesi yüksek.',
        prediction: 'KG VAR',
        confidence: 83,
        modelScore: 87,
        recentHistory: '8 Kazanç',
        expectedGoals: '2.90',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.65', odd2: '1.75', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.72', odd2: '1.82', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    },
    {
        id: 'porto-sporting',
        league: 'Liga Portugal',
        homeTeam: 'FC PORTO',
        awayTeam: 'SPORTING CP',
        matchTime: '21:30',
        matchDate: '2026-03-01',
        analysis: '',
        tacticalSummary: 'Portekiz derbileri genelde kontrollü başlar.',
        breakingPoint: 'Savunma disiplini.',
        bettingScenario: 'Portekiz derbileri genelde kontrollü başlar.',
        prediction: '2.5 ALT',
        confidence: 77,
        modelScore: 81,
        recentHistory: '5 Kazanç',
        expectedGoals: '1.95',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.80', odd2: '1.70', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.88', odd2: '1.78', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    },
    {
        id: 'palmeiras-saopaulo',
        league: 'Serie A (BRA)',
        homeTeam: 'PALMEIRAS',
        awayTeam: 'SÃO PAULO',
        matchTime: '22:00',
        matchDate: '2026-03-01',
        analysis: '',
        tacticalSummary: 'Derbi temposu yüksek ama kontrollü başlar.',
        breakingPoint: 'Orta saha mücadelesi.',
        bettingScenario: 'Derbi temposu yüksek ama kontrollü başlar.',
        prediction: '2.5 ALT',
        confidence: 79,
        modelScore: 83,
        recentHistory: '6 Kazanç',
        expectedGoals: '1.80',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.85', odd2: '1.75', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.92', odd2: '1.82', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    },
    {
        id: 'boca-independiente',
        league: 'Liga Profesional',
        homeTeam: 'BOCA JUNIORS',
        awayTeam: 'INDEPENDIENTE',
        matchTime: '01:00',
        matchDate: '2026-03-01',
        analysis: '',
        tacticalSummary: 'Arjantin’de derbiler genelde sert ve az gollü geçer.',
        breakingPoint: 'Kartlar ve sertlik.',
        bettingScenario: 'Arjantin’de derbiler genelde sert ve az gollü geçer.',
        prediction: '2.5 ALT / 1X',
        confidence: 82,
        modelScore: 86,
        recentHistory: '7 Kazanç',
        expectedGoals: '1.60',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.55', odd2: '1.65', link: 'https://google.com' },
            { name: 'MARSBAHİS', odd1: '1.62', odd2: '1.72', link: 'https://google.com', isHighest: true }
        ],
        createdAt: Date.now()
    }
    ,
    {
        id: 'new-match-0-1772621789626',
        league: 'Süper Lig',
        homeTeam: 'GALATASARAY',
        awayTeam: 'LIVERPOOL',
        matchTime: '21:00',
        matchDate: '2026-03-04',
        analysis: '',
        tacticalSummary: 'RAMS Park atmosferi ve Galatasaray\'ın hücum hattı skoru bulur, Liverpool karşılık verir.',
        breakingPoint: '724BAHİS oran avantajıyla KG Var seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'KG Var',
        confidence: 86,
        modelScore: 85,
        recentHistory: '5 Kazanç',
        expectedGoals: '2.44',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.12', odd2: '2.22', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.97', odd2: '2.07', link: 'https://google.com/' },
        ],
        createdAt: 1772621789626,
    },
    {
        id: 'new-match-1-1772621789626',
        league: 'Avrupa Ligleri',
        homeTeam: 'BEŞIKTAŞ',
        awayTeam: 'GALATASARAY',
        matchTime: '21:00',
        matchDate: '2026-03-05',
        analysis: '',
        tacticalSummary: 'Derbi stresi ve taktiksel savaş beraberliği ön plana çıkarıyor.',
        breakingPoint: '724BAHİS oran avantajıyla MS 0 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 0',
        confidence: 75,
        modelScore: 91,
        recentHistory: '6 Kazanç',
        expectedGoals: '2.80',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.77', odd2: '1.87', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.62', odd2: '1.72', link: 'https://google.com/' },
        ],
        createdAt: 1772621789627,
    },
    {
        id: 'new-match-2-1772621789626',
        league: 'Premier League',
        homeTeam: 'NEWCASTLE',
        awayTeam: 'BARCELONA',
        matchTime: '21:00',
        matchDate: '2026-03-06',
        analysis: '',
        tacticalSummary: 'Newcastle evinde çok sert savunma yapıyor, Barca zorlanır.',
        breakingPoint: '724BAHİS oran avantajıyla 2.5 Alt seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: '2.5 Alt',
        confidence: 84,
        modelScore: 83,
        recentHistory: '8 Kazanç',
        expectedGoals: '2.56',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.76', odd2: '1.86', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.61', odd2: '1.71', link: 'https://google.com/' },
        ],
        createdAt: 1772621789628,
    },
    {
        id: 'new-match-3-1772621789626',
        league: 'Avrupa Ligleri',
        homeTeam: 'ATALANTA',
        awayTeam: 'BAYERN MÜNIH',
        matchTime: '21:00',
        matchDate: '2026-03-07',
        analysis: '',
        tacticalSummary: 'İki takımın da oyun karakteri tamamen hücum odaklı.',
        breakingPoint: '724BAHİS oran avantajıyla 2.5 Üst seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: '2.5 Üst',
        confidence: 87,
        modelScore: 91,
        recentHistory: '8 Kazanç',
        expectedGoals: '2.99',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.54', odd2: '1.64', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.39', odd2: '1.49', link: 'https://google.com/' },
        ],
        createdAt: 1772621789629,
    },
    {
        id: 'new-match-4-1772621789626',
        league: 'Serie A',
        homeTeam: 'AC MILAN',
        awayTeam: 'INTER MILAN',
        matchTime: '21:00',
        matchDate: '2026-03-08',
        analysis: '',
        tacticalSummary: 'Milano derbisinde iki tarafın da gol yemeden bitirmesi zor.',
        breakingPoint: '724BAHİS oran avantajıyla KG Var seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'KG Var',
        confidence: 86,
        modelScore: 85,
        recentHistory: '6 Kazanç',
        expectedGoals: '1.80',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.35', odd2: '2.45', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '2.20', odd2: '2.30', link: 'https://google.com/' },
        ],
        createdAt: 1772621789630,
    },
    {
        id: 'new-match-5-1772621789626',
        league: 'Süper Lig',
        homeTeam: 'FENERBAHÇE',
        awayTeam: 'SAMSUNSPOR',
        matchTime: '21:00',
        matchDate: '2026-03-09',
        analysis: '',
        tacticalSummary: 'Fenerbahçe şampiyonluk yolunda Kadıköy’de hata yapmaz.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 83,
        modelScore: 89,
        recentHistory: '9 Kazanç',
        expectedGoals: '2.22',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.55', odd2: '1.65', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.40', odd2: '1.50', link: 'https://google.com/' },
        ],
        createdAt: 1772621789631,
    },
    {
        id: 'new-match-6-1772621789626',
        league: 'Avrupa Ligleri',
        homeTeam: 'MANCHESTER CITY',
        awayTeam: 'LEICESTER',
        matchTime: '21:00',
        matchDate: '2026-03-10',
        analysis: '',
        tacticalSummary: 'City sahasında vites arttırır, farka gider.',
        breakingPoint: '724BAHİS oran avantajıyla H1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'H1',
        confidence: 94,
        modelScore: 94,
        recentHistory: '5 Kazanç',
        expectedGoals: '2.73',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.79', odd2: '1.89', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.64', odd2: '1.74', link: 'https://google.com/' },
        ],
        createdAt: 1772621789632,
    },
    {
        id: 'new-match-7-1772621789626',
        league: 'Avrupa Ligleri',
        homeTeam: 'BRIGHTON',
        awayTeam: 'ARSENAL',
        matchTime: '21:00',
        matchDate: '2026-03-04',
        analysis: '',
        tacticalSummary: 'Arsenal\'in deplasman formu bu zorlu virajı geçmeye yeterli.',
        breakingPoint: '724BAHİS oran avantajıyla MS 2 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 2',
        confidence: 94,
        modelScore: 86,
        recentHistory: '6 Kazanç',
        expectedGoals: '3.25',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.13', odd2: '2.23', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.98', odd2: '2.08', link: 'https://google.com/' },
        ],
        createdAt: 1772621789633,
    },
    {
        id: 'new-match-8-1772621789626',
        league: 'La Liga',
        homeTeam: 'REAL MADRID',
        awayTeam: 'CELTA VIGO',
        matchTime: '21:00',
        matchDate: '2026-03-05',
        analysis: '',
        tacticalSummary: 'Bernabeu\'da Real Madrid sürprize izin vermez.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 94,
        modelScore: 93,
        recentHistory: '6 Kazanç',
        expectedGoals: '1.93',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.61', odd2: '1.71', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.46', odd2: '1.56', link: 'https://google.com/' },
        ],
        createdAt: 1772621789634,
    },
    {
        id: 'new-match-9-1772621789626',
        league: 'Avrupa Ligleri',
        homeTeam: 'ATHLETIC BILBAO',
        awayTeam: 'BARCELONA',
        matchTime: '21:00',
        matchDate: '2026-03-06',
        analysis: '',
        tacticalSummary: 'San Mames deplasmanı Barca için sezonun en zor maçlarından biri.',
        breakingPoint: '724BAHİS oran avantajıyla 10 Çifte Şans seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: '10 Çifte Şans',
        confidence: 78,
        modelScore: 85,
        recentHistory: '7 Kazanç',
        expectedGoals: '3.07',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.49', odd2: '1.59', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.34', odd2: '1.44', link: 'https://google.com/' },
        ],
        createdAt: 1772621789635,
    },
    {
        id: 'new-match-10-1772621789626',
        league: 'Avrupa Ligleri',
        homeTeam: 'MARSEILLE',
        awayTeam: 'LYON',
        matchTime: '21:00',
        matchDate: '2026-03-07',
        analysis: '',
        tacticalSummary: 'Fransa’nın en büyük rekabetlerinden biri, skorlu geçer.',
        breakingPoint: '724BAHİS oran avantajıyla 2.5 Üst seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: '2.5 Üst',
        confidence: 90,
        modelScore: 84,
        recentHistory: '7 Kazanç',
        expectedGoals: '2.40',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.55', odd2: '1.65', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.40', odd2: '1.50', link: 'https://google.com/' },
        ],
        createdAt: 1772621789636,
    },
    {
        id: 'new-match-11-1772621789626',
        league: 'Avrupa Ligleri',
        homeTeam: 'AJAX',
        awayTeam: 'PSV',
        matchTime: '21:00',
        matchDate: '2026-03-08',
        analysis: '',
        tacticalSummary: 'Hollanda klasikleri her zaman bol gollü ve tempoludur.',
        breakingPoint: '724BAHİS oran avantajıyla 3.5 Üst seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: '3.5 Üst',
        confidence: 90,
        modelScore: 87,
        recentHistory: '7 Kazanç',
        expectedGoals: '2.28',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.76', odd2: '1.86', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.61', odd2: '1.71', link: 'https://google.com/' },
        ],
        createdAt: 1772621789637,
    },
    {
        id: 'new-match-12-1772621789626',
        league: 'Avrupa Ligleri',
        homeTeam: 'BAYERN MÜNIH',
        awayTeam: 'M\'GLADBACH',
        matchTime: '21:00',
        matchDate: '2026-03-09',
        analysis: '',
        tacticalSummary: 'Bayern maça hızlı başlayıp fişi ilk yarıdan çeker.',
        breakingPoint: '724BAHİS oran avantajıyla İY 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'İY 1',
        confidence: 83,
        modelScore: 81,
        recentHistory: '9 Kazanç',
        expectedGoals: '3.40',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.58', odd2: '1.68', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.43', odd2: '1.53', link: 'https://google.com/' },
        ],
        createdAt: 1772621789638,
    },
    {
        id: 'new-match-13-1772621789626',
        league: 'Bundesliga',
        homeTeam: 'LEVERKUSEN',
        awayTeam: 'FREIBURG',
        matchTime: '21:00',
        matchDate: '2026-03-10',
        analysis: '',
        tacticalSummary: 'Xabi Alonso\'nun sistemi iç sahada kusursuz işliyor.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 84,
        modelScore: 81,
        recentHistory: '5 Kazanç',
        expectedGoals: '2.26',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.82', odd2: '1.92', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.67', odd2: '1.77', link: 'https://google.com/' },
        ],
        createdAt: 1772621789639,
    },
    {
        id: 'new-match-14-1772621789626',
        league: 'Serie A',
        homeTeam: 'NAPOLI',
        awayTeam: 'TORINO',
        matchTime: '21:00',
        matchDate: '2026-03-04',
        analysis: '',
        tacticalSummary: 'Napoli taraftar desteğiyle tek farklı da olsa kazanır.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 88,
        modelScore: 84,
        recentHistory: '5 Kazanç',
        expectedGoals: '2.08',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.68', odd2: '1.78', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.53', odd2: '1.63', link: 'https://google.com/' },
        ],
        createdAt: 1772621789640,
    },
    {
        id: 'new-match-15-1772621789626',
        league: 'Serie A',
        homeTeam: 'JUVENTUS',
        awayTeam: 'PISA',
        matchTime: '21:00',
        matchDate: '2026-03-05',
        analysis: '',
        tacticalSummary: 'Juve kontrollü oyunuyla skoru korur, maç kısır geçer.',
        breakingPoint: '724BAHİS oran avantajıyla 3.5 Alt seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: '3.5 Alt',
        confidence: 79,
        modelScore: 93,
        recentHistory: '6 Kazanç',
        expectedGoals: '2.05',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.22', odd2: '2.32', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '2.07', odd2: '2.17', link: 'https://google.com/' },
        ],
        createdAt: 1772621789641,
    },
    {
        id: 'new-match-16-1772621789626',
        league: 'Avrupa Ligleri',
        homeTeam: 'SPORTING CP',
        awayTeam: 'BENFICA',
        matchTime: '21:00',
        matchDate: '2026-03-06',
        analysis: '',
        tacticalSummary: 'Portekiz derbisinde iki dev de skora katkı yapar.',
        breakingPoint: '724BAHİS oran avantajıyla KG Var seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'KG Var',
        confidence: 89,
        modelScore: 80,
        recentHistory: '5 Kazanç',
        expectedGoals: '2.43',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.74', odd2: '1.84', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.59', odd2: '1.69', link: 'https://google.com/' },
        ],
        createdAt: 1772621789642,
    },
    {
        id: 'new-match-17-1772621789626',
        league: 'Premier League',
        homeTeam: 'CHELSEA',
        awayTeam: 'ASTON VILLA',
        matchTime: '21:00',
        matchDate: '2026-03-07',
        analysis: '',
        tacticalSummary: 'Villa\'nın geçiş hücumları maçı üste taşır.',
        breakingPoint: '724BAHİS oran avantajıyla 2.5 Üst seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: '2.5 Üst',
        confidence: 87,
        modelScore: 90,
        recentHistory: '6 Kazanç',
        expectedGoals: '2.24',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.10', odd2: '2.20', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.95', odd2: '2.05', link: 'https://google.com/' },
        ],
        createdAt: 1772621789643,
    },
    {
        id: 'new-match-18-1772621789626',
        league: 'Avrupa Ligleri',
        homeTeam: 'TOTTENHAM',
        awayTeam: 'CRYSTAL PALACE',
        matchTime: '21:00',
        matchDate: '2026-03-08',
        analysis: '',
        tacticalSummary: 'Spurs evinde tempo yaparak galibiyete uzanır.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 86,
        modelScore: 93,
        recentHistory: '6 Kazanç',
        expectedGoals: '1.58',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.53', odd2: '1.63', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.38', odd2: '1.48', link: 'https://google.com/' },
        ],
        createdAt: 1772621789644,
    },
    {
        id: 'new-match-19-1772621789626',
        league: 'Avrupa Ligleri',
        homeTeam: 'DORTMUND',
        awayTeam: 'FC KÖLN',
        matchTime: '21:00',
        matchDate: '2026-03-09',
        analysis: '',
        tacticalSummary: 'Dortmund\'un iç saha baskısı Köln\'ü hata yapmaya zorlar.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 93,
        modelScore: 88,
        recentHistory: '9 Kazanç',
        expectedGoals: '2.14',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.89', odd2: '1.99', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.74', odd2: '1.84', link: 'https://google.com/' },
        ],
        createdAt: 1772621789645,
    },
    {
        id: 'new-match-20-1772621789626',
        league: 'Serie A',
        homeTeam: 'ROMA',
        awayTeam: 'GENOA',
        matchTime: '21:00',
        matchDate: '2026-03-10',
        analysis: '',
        tacticalSummary: 'Roma Olimpiyat Stadı\'nda puan kaybı yaşamaz.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 90,
        modelScore: 89,
        recentHistory: '6 Kazanç',
        expectedGoals: '3.13',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.91', odd2: '2.01', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.76', odd2: '1.86', link: 'https://google.com/' },
        ],
        createdAt: 1772621789646,
    },
    {
        id: 'new-match-21-1772621789626',
        league: 'Avrupa Ligleri',
        homeTeam: 'LAZIO',
        awayTeam: 'SASSUOLO',
        matchTime: '21:00',
        matchDate: '2026-03-04',
        analysis: '',
        tacticalSummary: 'Lazio\'nun hücum hattı formda, Sassuolo savunması zayıf.',
        breakingPoint: '724BAHİS oran avantajıyla 2.5 Üst seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: '2.5 Üst',
        confidence: 78,
        modelScore: 85,
        recentHistory: '6 Kazanç',
        expectedGoals: '1.78',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.13', odd2: '2.23', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.98', odd2: '2.08', link: 'https://google.com/' },
        ],
        createdAt: 1772621789647,
    },
    {
        id: 'new-match-22-1772621789627',
        league: 'La Liga',
        homeTeam: 'ATLETICO MADRID',
        awayTeam: 'REAL SOCIEDAD',
        matchTime: '21:00',
        matchDate: '2026-03-05',
        analysis: '',
        tacticalSummary: 'Simeone\'nin takımı bu tip kritik maçları tek golle çözmeyi bilir.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 83,
        modelScore: 82,
        recentHistory: '8 Kazanç',
        expectedGoals: '3.11',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.81', odd2: '1.91', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.66', odd2: '1.76', link: 'https://google.com/' },
        ],
        createdAt: 1772621789648,
    },
    {
        id: 'new-match-23-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'SEVILLA',
        awayTeam: 'RAYO VALLECANO',
        matchTime: '21:00',
        matchDate: '2026-03-06',
        analysis: '',
        tacticalSummary: 'Sevilla evinde alt sıralardan uzaklaşmak için kazanmak zorunda.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 79,
        modelScore: 83,
        recentHistory: '5 Kazanç',
        expectedGoals: '1.80',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.81', odd2: '1.91', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.66', odd2: '1.76', link: 'https://google.com/' },
        ],
        createdAt: 1772621789649,
    },
    {
        id: 'new-match-24-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'VALENCIA',
        awayTeam: 'ALAVES',
        matchTime: '21:00',
        matchDate: '2026-03-07',
        analysis: '',
        tacticalSummary: 'İki takımın da önceliği savunma, az gol çıkar.',
        breakingPoint: '724BAHİS oran avantajıyla 2.5 Alt seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: '2.5 Alt',
        confidence: 87,
        modelScore: 85,
        recentHistory: '5 Kazanç',
        expectedGoals: '2.38',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.16', odd2: '2.26', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '2.01', odd2: '2.11', link: 'https://google.com/' },
        ],
        createdAt: 1772621789650,
    },
    {
        id: 'new-match-25-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'KAYSERISPOR',
        awayTeam: 'TRABZONSPOR',
        matchTime: '21:00',
        matchDate: '2026-03-08',
        analysis: '',
        tacticalSummary: 'Trabzonspor deplasmanda gol bulur ama kalesini kapatamaz.',
        breakingPoint: '724BAHİS oran avantajıyla KG Var seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'KG Var',
        confidence: 83,
        modelScore: 82,
        recentHistory: '5 Kazanç',
        expectedGoals: '1.93',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.25', odd2: '2.35', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '2.10', odd2: '2.20', link: 'https://google.com/' },
        ],
        createdAt: 1772621789651,
    },
    {
        id: 'new-match-26-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'KONYASPOR',
        awayTeam: 'KASIMPAŞA',
        matchTime: '21:00',
        matchDate: '2026-03-09',
        analysis: '',
        tacticalSummary: 'İki denk takımın mücadelesinde puanlar paylaşılır.',
        breakingPoint: '724BAHİS oran avantajıyla MS 0 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 0',
        confidence: 90,
        modelScore: 88,
        recentHistory: '8 Kazanç',
        expectedGoals: '2.53',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.73', odd2: '1.83', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.58', odd2: '1.68', link: 'https://google.com/' },
        ],
        createdAt: 1772621789652,
    },
    {
        id: 'new-match-27-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'EYÜPSPOR',
        awayTeam: 'KOCAELISPOR',
        matchTime: '21:00',
        matchDate: '2026-03-10',
        analysis: '',
        tacticalSummary: 'Arda Turan\'ın öğrencileri iç saha avantajını kullanır.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 86,
        modelScore: 80,
        recentHistory: '6 Kazanç',
        expectedGoals: '3.01',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.94', odd2: '2.04', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.79', odd2: '1.89', link: 'https://google.com/' },
        ],
        createdAt: 1772621789653,
    },
    {
        id: 'new-match-28-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'LEIPZIG',
        awayTeam: 'AUGSBURG',
        matchTime: '21:00',
        matchDate: '2026-03-04',
        analysis: '',
        tacticalSummary: 'Leipzig tempoyu yükselttiğinde farkı açar.',
        breakingPoint: '724BAHİS oran avantajıyla H1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'H1',
        confidence: 85,
        modelScore: 89,
        recentHistory: '8 Kazanç',
        expectedGoals: '2.46',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.76', odd2: '1.86', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.61', odd2: '1.71', link: 'https://google.com/' },
        ],
        createdAt: 1772621789654,
    },
    {
        id: 'new-match-29-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'RIVER PLATE',
        awayTeam: 'INDEPENDIENTE',
        matchTime: '21:00',
        matchDate: '2026-03-05',
        analysis: '',
        tacticalSummary: 'Arjantin\'de River Plate sahasında her zaman favori.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 76,
        modelScore: 85,
        recentHistory: '7 Kazanç',
        expectedGoals: '3.13',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.95', odd2: '2.05', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.80', odd2: '1.90', link: 'https://google.com/' },
        ],
        createdAt: 1772621789655,
    },
    {
        id: 'new-match-30-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'FLAMENGO',
        awayTeam: 'FLUMINENSE',
        matchTime: '21:00',
        matchDate: '2026-03-06',
        analysis: '',
        tacticalSummary: 'Brezilya derbisinde gerginlik ve sertlik ön planda olur.',
        breakingPoint: '724BAHİS oran avantajıyla 2.5 Alt seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: '2.5 Alt',
        confidence: 89,
        modelScore: 90,
        recentHistory: '7 Kazanç',
        expectedGoals: '3.05',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.71', odd2: '1.81', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.56', odd2: '1.66', link: 'https://google.com/' },
        ],
        createdAt: 1772621789656,
    },
    {
        id: 'new-match-31-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'GIRONA',
        awayTeam: 'LEVANTE',
        matchTime: '21:00',
        matchDate: '2026-03-07',
        analysis: '',
        tacticalSummary: 'Girona bu sezonun peri masalını evinde sürdürür.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 90,
        modelScore: 90,
        recentHistory: '5 Kazanç',
        expectedGoals: '3.13',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.15', odd2: '2.25', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '2.00', odd2: '2.10', link: 'https://google.com/' },
        ],
        createdAt: 1772621789657,
    },
    {
        id: 'new-match-32-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'PORTO',
        awayTeam: 'BRAGA',
        matchTime: '21:00',
        matchDate: '2026-03-08',
        analysis: '',
        tacticalSummary: 'Kupa maçında iki takım da açık futbol sergiler.',
        breakingPoint: '724BAHİS oran avantajıyla KG Var seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'KG Var',
        confidence: 77,
        modelScore: 80,
        recentHistory: '8 Kazanç',
        expectedGoals: '2.62',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.12', odd2: '2.22', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.97', odd2: '2.07', link: 'https://google.com/' },
        ],
        createdAt: 1772621789658,
    },
    {
        id: 'new-match-33-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'RANGERS',
        awayTeam: 'ABERDEEN',
        matchTime: '21:00',
        matchDate: '2026-03-09',
        analysis: '',
        tacticalSummary: 'Rangers şampiyonluk yarışında hata lüksü olmayan bir maçta.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 78,
        modelScore: 87,
        recentHistory: '9 Kazanç',
        expectedGoals: '2.60',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.59', odd2: '1.69', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.44', odd2: '1.54', link: 'https://google.com/' },
        ],
        createdAt: 1772621789659,
    },
    {
        id: 'new-match-34-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'BENFICA',
        awayTeam: 'RIO AVE',
        matchTime: '21:00',
        matchDate: '2026-03-10',
        analysis: '',
        tacticalSummary: 'Benfica ilk 45 dakikada baskıyla skoru alır.',
        breakingPoint: '724BAHİS oran avantajıyla İY 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'İY 1',
        confidence: 79,
        modelScore: 83,
        recentHistory: '9 Kazanç',
        expectedGoals: '3.03',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.47', odd2: '1.57', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.32', odd2: '1.42', link: 'https://google.com/' },
        ],
        createdAt: 1772621789660,
    },
    {
        id: 'new-match-35-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'MAN UNITED',
        awayTeam: 'WEST HAM',
        matchTime: '21:00',
        matchDate: '2026-03-04',
        analysis: '',
        tacticalSummary: 'United güven vermese de evinde yenilmesi zor.',
        breakingPoint: '724BAHİS oran avantajıyla 10 Çifte Şans seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: '10 Çifte Şans',
        confidence: 75,
        modelScore: 82,
        recentHistory: '8 Kazanç',
        expectedGoals: '1.73',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.27', odd2: '2.37', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '2.12', odd2: '2.22', link: 'https://google.com/' },
        ],
        createdAt: 1772621789661,
    },
    {
        id: 'new-match-36-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'LILLE',
        awayTeam: 'NICE',
        matchTime: '21:00',
        matchDate: '2026-03-05',
        analysis: '',
        tacticalSummary: 'İki takım da savunma disipliniyle biliniyor.',
        breakingPoint: '724BAHİS oran avantajıyla 2.5 Alt seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: '2.5 Alt',
        confidence: 84,
        modelScore: 87,
        recentHistory: '9 Kazanç',
        expectedGoals: '2.78',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.21', odd2: '2.31', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '2.06', odd2: '2.16', link: 'https://google.com/' },
        ],
        createdAt: 1772621789662,
    },
    {
        id: 'new-match-37-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'ATALANTA',
        awayTeam: 'UDINESE',
        matchTime: '21:00',
        matchDate: '2026-03-06',
        analysis: '',
        tacticalSummary: 'Atalanta\'nın iç saha performansı Udinese\'yi bozar.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 75,
        modelScore: 87,
        recentHistory: '9 Kazanç',
        expectedGoals: '1.78',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.17', odd2: '2.27', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '2.02', odd2: '2.12', link: 'https://google.com/' },
        ],
        createdAt: 1772621789663,
    },
    {
        id: 'new-match-38-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'FRANKFURT',
        awayTeam: 'ST. PAULI',
        matchTime: '21:00',
        matchDate: '2026-03-07',
        analysis: '',
        tacticalSummary: 'Frankfurt kadro kalitesiyle üstünlük kurar.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 84,
        modelScore: 82,
        recentHistory: '7 Kazanç',
        expectedGoals: '3.46',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.46', odd2: '1.56', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.31', odd2: '1.41', link: 'https://google.com/' },
        ],
        createdAt: 1772621789664,
    },
    {
        id: 'new-match-39-1772621789627',
        league: 'Avrupa Ligleri',
        homeTeam: 'BETIS',
        awayTeam: 'VILLARREAL',
        matchTime: '21:00',
        matchDate: '2026-03-08',
        analysis: '',
        tacticalSummary: 'İspanya\'nın en keyifli maçlarından biri olmaya aday.',
        breakingPoint: '724BAHİS oran avantajıyla KG Var seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'KG Var',
        confidence: 82,
        modelScore: 90,
        recentHistory: '5 Kazanç',
        expectedGoals: '1.51',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.14', odd2: '2.24', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.99', odd2: '2.09', link: 'https://google.com/' },
        ],
        createdAt: 1772621789665,
    },
    {
        id: 'new-match-40-1772621789627',
        league: 'Süper Lig',
        homeTeam: 'FENERBAHÇE BEKO',
        awayTeam: 'MONACO',
        matchTime: '21:00',
        matchDate: '2026-03-09',
        analysis: '',
        tacticalSummary: 'Saras yönetimindeki Fener evinde Euroleague\'in en iyilerinden.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 94,
        modelScore: 81,
        recentHistory: '9 Kazanç',
        expectedGoals: 'N/A',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.19', odd2: '2.29', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '2.04', odd2: '2.14', link: 'https://google.com/' },
        ],
        createdAt: 1772621789666,
    },
    {
        id: 'new-match-41-1772621789627',
        league: 'EuroLeague',
        homeTeam: 'ANADOLU EFES',
        awayTeam: 'ASVEL',
        matchTime: '21:00',
        matchDate: '2026-03-10',
        analysis: '',
        tacticalSummary: 'Efes play-off yolunda hata yapmaz, farka gider.',
        breakingPoint: '724BAHİS oran avantajıyla H1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'H1',
        confidence: 85,
        modelScore: 84,
        recentHistory: '6 Kazanç',
        expectedGoals: 'N/A',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.31', odd2: '2.41', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '2.16', odd2: '2.26', link: 'https://google.com/' },
        ],
        createdAt: 1772621789667,
    },
    {
        id: 'new-match-42-1772621789627',
        league: 'La Liga',
        homeTeam: 'BARCELONA',
        awayTeam: 'MILAN',
        matchTime: '21:00',
        matchDate: '2026-03-04',
        analysis: '',
        tacticalSummary: 'Barca evinde sert savunmasıyla Milano\'yu durdurur.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 89,
        modelScore: 92,
        recentHistory: '9 Kazanç',
        expectedGoals: 'N/A',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.18', odd2: '2.28', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '2.03', odd2: '2.13', link: 'https://google.com/' },
        ],
        createdAt: 1772621789668,
    },
    {
        id: 'new-match-43-1772621789627',
        league: 'EuroLeague',
        homeTeam: 'OLYMPIACOS',
        awayTeam: 'PANATHINAIKOS',
        matchTime: '21:00',
        matchDate: '2026-03-05',
        analysis: '',
        tacticalSummary: 'Yunan derbisinde savunmalar konuşur, düşük skor çıkar.',
        breakingPoint: '724BAHİS oran avantajıyla 155.5 Alt seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: '155.5 Alt',
        confidence: 91,
        modelScore: 92,
        recentHistory: '8 Kazanç',
        expectedGoals: 'N/A',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.66', odd2: '1.76', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.51', odd2: '1.61', link: 'https://google.com/' },
        ],
        createdAt: 1772621789669,
    },
    {
        id: 'new-match-44-1772621789627',
        league: 'La Liga',
        homeTeam: 'REAL MADRID',
        awayTeam: 'VIRTUS BOLOGNA',
        matchTime: '21:00',
        matchDate: '2026-03-06',
        analysis: '',
        tacticalSummary: 'Real Madrid kalitesiyle sahadan galip ayrılır.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 82,
        modelScore: 88,
        recentHistory: '7 Kazanç',
        expectedGoals: 'N/A',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.76', odd2: '1.86', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.61', odd2: '1.71', link: 'https://google.com/' },
        ],
        createdAt: 1772621789670,
    },
    {
        id: 'new-match-45-1772621789627',
        league: 'EuroLeague',
        homeTeam: 'CRVENA ZVEZDA',
        awayTeam: 'BAYERN',
        matchTime: '21:00',
        matchDate: '2026-03-07',
        analysis: '',
        tacticalSummary: 'Belgrad cehenneminden Bayern\'in çıkması zor.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 93,
        modelScore: 93,
        recentHistory: '9 Kazanç',
        expectedGoals: 'N/A',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.55', odd2: '1.65', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.40', odd2: '1.50', link: 'https://google.com/' },
        ],
        createdAt: 1772621789671,
    },
    {
        id: 'new-match-46-1772621789627',
        league: 'NBA',
        homeTeam: 'NY KNICKS',
        awayTeam: 'OKC THUNDER',
        matchTime: '21:00',
        matchDate: '2026-03-08',
        analysis: '',
        tacticalSummary: 'İki takımın da savunma disiplini skoru aşağı çeker.',
        breakingPoint: '724BAHİS oran avantajıyla 215.5 Alt seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: '215.5 Alt',
        confidence: 81,
        modelScore: 88,
        recentHistory: '9 Kazanç',
        expectedGoals: 'N/A',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.18', odd2: '2.28', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '2.03', odd2: '2.13', link: 'https://google.com/' },
        ],
        createdAt: 1772621789672,
    },
    {
        id: 'new-match-47-1772621789627',
        league: 'NBA',
        homeTeam: 'BOSTON CELTICS',
        awayTeam: 'CHARLOTTE',
        matchTime: '21:00',
        matchDate: '2026-03-09',
        analysis: '',
        tacticalSummary: 'NBA\'in lideri Boston evinde çok rahat kazanır.',
        breakingPoint: '724BAHİS oran avantajıyla MS 1 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 1',
        confidence: 90,
        modelScore: 94,
        recentHistory: '5 Kazanç',
        expectedGoals: 'N/A',
        bookieOdds: [
            { name: '724BAHİS', odd1: '1.71', odd2: '1.81', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '1.56', odd2: '1.66', link: 'https://google.com/' },
        ],
        createdAt: 1772621789673,
    },
    {
        id: 'new-match-48-1772621789627',
        league: 'NBA',
        homeTeam: 'PHOENIX SUNS',
        awayTeam: 'MILWAUKEE',
        matchTime: '21:00',
        matchDate: '2026-03-10',
        analysis: '',
        tacticalSummary: 'Yıldızların düellosunda bol skor bekliyorum.',
        breakingPoint: '724BAHİS oran avantajıyla 228.5 Üst seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: '228.5 Üst',
        confidence: 82,
        modelScore: 87,
        recentHistory: '9 Kazanç',
        expectedGoals: 'N/A',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.28', odd2: '2.38', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '2.13', odd2: '2.23', link: 'https://google.com/' },
        ],
        createdAt: 1772621789674,
    },
    {
        id: 'new-match-49-1772621789627',
        league: 'NBA',
        homeTeam: 'MINNESOTA',
        awayTeam: 'LA LAKERS',
        matchTime: '21:00',
        matchDate: '2026-03-04',
        analysis: '',
        tacticalSummary: 'Lakers tecrübesiyle kritik deplasmandan galibiyet çıkarır.',
        breakingPoint: '724BAHİS oran avantajıyla MS 2 seçeneği mantıklıdır.',
        bettingScenario: '724BAHİS yüksek oran avantajını değerlendirerek bahis yapılabilir.',
        prediction: 'MS 2',
        confidence: 75,
        modelScore: 89,
        recentHistory: '7 Kazanç',
        expectedGoals: 'N/A',
        bookieOdds: [
            { name: '724BAHİS', odd1: '2.34', odd2: '2.44', link: 'https://724bahis.net', isHighest: true },
            { name: 'MARSBAHİS', odd1: '2.19', odd2: '2.29', link: 'https://google.com/' },
        ],
        createdAt: 1772621789675,
    }
];

export const demoCoupons: any[] = [ // Using any for simplicity or I can import Coupon type
    {
        id: 'national-matches-31mar',
        title: 'MİLLİ MAÇ ÖZEL KASASI',
        riskLevel: 'MEDIUM',
        matches: [
            { matchId: 'kosovo-turkey-20260331', homeTeam: 'KOSOVA', awayTeam: 'TÜRKİYE', prediction: 'MS 2', odd: '1.92' },
            { matchId: 'bosnia-italy-20260331', homeTeam: 'BOSNA HERSEK', awayTeam: 'İTALYA', prediction: 'MS 2', odd: '1.75' },
            { matchId: 'czechia-denmark-20260331', homeTeam: 'ÇEKYA', awayTeam: 'DANİMARKA', prediction: 'DANIMARKA 02 ÇŞ', odd: '1.68' }
        ],
        totalOdd: '5.64',
        date: '2026-03-31'
    },
    {
        id: 'low-risk-01',
        title: 'GÜNÜN KASASI',
        riskLevel: 'LOW',
        matches: [
            { matchId: 'porto-arouca', homeTeam: 'PORTO', awayTeam: 'AROUCA', prediction: '1.5 ÜST', odd: '1.25' },
            { matchId: 'trabzon-karagumruk', homeTeam: 'TRABZONSPOR', awayTeam: 'KARAGÜMRÜK', prediction: '1X', odd: '1.28' },
            { matchId: 'augsburg-koln', homeTeam: 'AUGSBURG', awayTeam: 'KÖLN', prediction: '3.5 ALT', odd: '1.35' }
        ],
        totalOdd: '2.16',
        date: '2026-03-01'
    },
    {
        id: 'medium-risk-01',
        title: 'İDEAL KUPON',
        riskLevel: 'MEDIUM',
        matches: [
            { matchId: 'wolverhampton-villa', homeTeam: 'WOLVES', awayTeam: 'ASTON VILLA', prediction: 'KG VAR', odd: '1.72' },
            { matchId: 'strasbourg-lens', homeTeam: 'STRASBOURG', awayTeam: 'LENS', prediction: '2.5 ÜST', odd: '1.90' }
        ],
        totalOdd: '3.26',
        date: '2026-03-01'
    },
    {
        id: 'high-risk-02',
        title: 'SİSTEM / SÜRPRİZ',
        riskLevel: 'HIGH',
        matches: [
            { matchId: 'levante-alaves', homeTeam: 'LEVANTE', awayTeam: 'ALAVÉS', prediction: 'İY 0', odd: '2.10' },
            { matchId: 'parma-cagliari', homeTeam: 'PARMA', awayTeam: 'CAGLIARI', prediction: 'MS 1', odd: '2.45' }
        ],
        totalOdd: '5.14',
        date: '2026-03-02'
    },
    {
        id: 'low-risk-03',
        title: 'GARANTİ KUPON',
        riskLevel: 'LOW',
        matches: [
            { matchId: 'city-utd', homeTeam: 'MAN CITY', awayTeam: 'MAN UTD', prediction: 'MS 1', odd: '1.40' },
            { matchId: 'real-barca', homeTeam: 'REAL MADRID', awayTeam: 'BARCELONA', prediction: '1.5 ÜST', odd: '1.22' }
        ],
        totalOdd: '1.71',
        date: '2026-03-03'
    }
    ,
    {
        id: 'betlivo-gunun-kasasi',
        title: '724BAHİS VIP KASA',
        riskLevel: 'LOW',
        matches: [
            { matchId: 'new-c1-1', homeTeam: 'GALATASARAY', awayTeam: 'LIVERPOOL', prediction: 'KG Var', odd: '1.65' },
            { matchId: 'new-c1-2', homeTeam: 'BAYERN MÜNİH', awayTeam: 'M\'GLADBACH', prediction: 'İY 1', odd: '1.50' },
            { matchId: 'new-c1-3', homeTeam: 'FENERBAHÇE BEKO', awayTeam: 'MONACO', prediction: 'MS 1', odd: '1.45' },
        ],
        totalOdd: '3.59',
        date: '2026-03-04'
    }, ,
    {
        id: 'betlivo-ideal',
        title: '724BAHİS GÜNÜN KOMBİNESİ',
        riskLevel: 'MEDIUM',
        matches: [
            { matchId: 'new-c2-1', homeTeam: 'BEŞİKTAŞ', awayTeam: 'GALATASARAY', prediction: 'MS 0', odd: '2.80' },
            { matchId: 'new-c2-2', homeTeam: 'AC MILAN', awayTeam: 'INTER', prediction: 'KG Var', odd: '1.75' },
            { matchId: 'new-c2-3', homeTeam: 'BOSTON CELTICS', awayTeam: 'CHARLOTTE', prediction: 'MS 1', odd: '1.25' },
        ],
        totalOdd: '6.12',
        date: '2026-03-05'
    }, ,
    {
        id: 'betlivo-kazanc',
        title: 'AVRUPA YÜKSEK ORAN',
        riskLevel: 'HIGH',
        matches: [
            { matchId: 'new-c3-1', homeTeam: 'ATALANTA', awayTeam: 'BAYERN MÜNİH', prediction: '2.5 ÜST', odd: '1.85' },
            { matchId: 'new-c3-2', homeTeam: 'PHOENIX SUNS', awayTeam: 'MILWAUKEE', prediction: '228.5 Üst', odd: '1.90' },
            { matchId: 'new-c3-3', homeTeam: 'AJAX', awayTeam: 'PSV', prediction: '3.5 ÜST', odd: '2.40' },
        ],
        totalOdd: '8.43',
        date: '2026-03-06'
    },
];

export const demoNews: NewsArticle[] = [
    {
        id: 'news-1',
        title: 'Galatasaray, Şampiyonlar Ligi\'nde Liverpool\'u Ağırlıyor: Dev Gece!',
        slug: 'galatasaray-sampiyonlar-ligi-liverpool',
        excerpt: 'RAMS Park\'ta devler karşı karşıya. Galatasaray taraftarının desteğiyle imkansızı başarmayı hedefliyor.',
        content: '<h2>Dünya Futbolunun Gözü İstanbul\'da</h2><p>Galatasaray, Şampiyonlar Ligi\'nin en prestijli gecelerinden birine ev sahipliği yapacak. Liverpool karşısında RAMS Park\'ta 60.000 kişilik tribünler yangın yeri olacak.</p><p>Cimbom\'un hücum hattında Icardi ve Zaniolo\'nun uyumu dikkat çekerken, Liverpool\'un Salah-Núñez ikilisi her an patlayabilecek tehlike.</p><h2>Taktik Analiz</h2><p>Okan Buruk\'un takımı yüksek baskı oyunuyla Liverpool\'u kendi yarısına hapsetmeyi planlıyor. Klopp ise geçiş oyunundaki kalitesiyle kontra ataklara güveniyor.</p><p>Maçın kırılma noktası ilk 15 dakika olacak. Erken gol bulan taraf büyük avantaj yakalayacak.</p>',
        category: 'Futbol',
        image: 'https://picsum.photos/seed/gs-liv/800/450',
        authorId: 'author-1',
        authorName: 'Spor Editörü',
        views: 1247,
        status: 'published',
        seoTitle: 'Galatasaray Liverpool Şampiyonlar Ligi Maçı',
        seoDescription: 'Galatasaray Şampiyonlar Ligi\'nde Liverpool\'u RAMS Park\'ta ağırlıyor.',
        createdAt: Date.now() - 86400000,
        updatedAt: Date.now() - 86400000,
    },
    {
        id: 'news-2',
        title: 'Fenerbahçe Beko, EuroLeague\'de Monaco\'yu Devirdi!',
        slug: 'fenerbahce-beko-euroleague-monaco',
        excerpt: 'Saras yönetimindeki Fenerbahçe Beko, taraftar desteğiyle Monaco\'yu mağlup etti.',
        content: '<h2>Ülker Spor Salonu Coştu</h2><p>Fenerbahçe Beko, EuroLeague\'in kritik maçında Monaco\'yu 85-72 mağlup ederek play-off umutlarını güçlendirdi.</p><p>Maçın MVP\'si 24 sayı, 8 asist ile oynayan De Colo oldu. Taraftar 3. çeyrekte yapılan 12-0\'lık seriyle salonu inletti.</p><h2>Play-Off Yarışı</h2><p>Bu galibiyetle 18-10\'a yükselen Fenerbahçe Beko, play-off\'ta ev sahibi avantajı için kritik bir adım attı.</p>',
        category: 'Basketbol',
        image: 'https://picsum.photos/seed/fb-beko/800/450',
        authorId: 'author-1',
        authorName: 'Spor Editörü',
        views: 893,
        status: 'published',
        createdAt: Date.now() - 172800000,
        updatedAt: Date.now() - 172800000,
    },
    {
        id: 'news-3',
        title: 'Verstappen, Bahreyn GP\'sinde Sezona Galibiyetle Başladı',
        slug: 'verstappen-bahreyn-gp-galibiyet',
        excerpt: 'Max Verstappen, 2026 sezonunun ilk yarışında dominant performansla zirveye çıktı.',
        content: '<h2>Red Bull Yine Zirvede</h2><p>Formula 1\'in 2026 sezonu Bahreyn Grand Prix\'si ile start aldı. Max Verstappen, pole pozisyonundan başladığı yarışta rakiplerine şans tanımadı.</p><p>Hollandalı pilot, en yakın rakibi Norris\'in 12 saniye önünde finiş çizgisini geçerek sezonun ilk zaferini elde etti.</p><h2>Takım Sıralaması</h2><p>Red Bull-Honda, çifte podyumla sezona mükemmel bir başlangıç yaparken, Ferrari\'nin yeni aracı beklentilerin altında kaldı.</p>',
        category: 'Formula 1',
        image: 'https://picsum.photos/seed/f1-ver/800/450',
        authorId: 'author-1',
        authorName: 'Spor Editörü',
        views: 2150,
        status: 'published',
        createdAt: Date.now() - 259200000,
        updatedAt: Date.now() - 259200000,
    },
    {
        id: 'news-4',
        title: 'Marc Marquez, MotoGP Katar\'da Muhteşem Dönüş Yaptı',
        slug: 'marc-marquez-motogp-katar-donus',
        excerpt: 'Ducati formasıyla Marquez, Lusail\'de podyuma çıkarak geri dönüşünü ilan etti.',
        content: '<h2>Marquez Geri Döndü!</h2><p>MotoGP 2026 sezonu Katar GP\'si, Marc Marquez\'in muhteşem dönüşüne sahne oldu. Ducati resmi takımıyla yarışan İspanyol pilot, ikinci sıradan start alarak podyumda bitirdi.</p><p>Yarışı kazanan Bagnaia olurken, üçüncülüğü Martin aldı. Marquez\'in Ducati\'deki uyum süreci beklentilerin ötesinde ilerliyor.</p>',
        category: 'MotoGP',
        image: 'https://picsum.photos/seed/motogp-mm/800/450',
        authorId: 'author-1',
        authorName: 'Spor Editörü',
        views: 678,
        status: 'published',
        createdAt: Date.now() - 345600000,
        updatedAt: Date.now() - 345600000,
    },
    {
        id: 'news-5',
        title: 'Toprak Razgatlıoğlu, Superbike Şampiyonasında Liderliğini Sürdürüyor',
        slug: 'toprak-razgatlioglu-superbike-liderlik',
        excerpt: 'Türk pilot, Phillip Island\'da çifte zaferle puan farkını açtı.',
        content: '<h2>Türk Bayrağı Zirvede</h2><p>Superbike Dünya Şampiyonası\'nda BMW formasıyla yarışan Toprak Razgatlıoğlu, Avustralya\'nın Phillip Island pistinde iki yarışı da kazanarak liderliğini pekiştirdi.</p><p>Toprak, son 5 yarışın 4\'ünü kazanarak rakiplerinin 45 puan önüne geçti. BMW M1000RR ile mükemmel uyum sağlayan Türk pilot, ikinci şampiyonluğuna doğru emin adımlarla ilerliyor.</p>',
        category: 'Superbike',
        image: 'https://picsum.photos/seed/sbk-tr/800/450',
        authorId: 'author-1',
        authorName: 'Spor Editörü',
        views: 1560,
        status: 'published',
        createdAt: Date.now() - 432000000,
        updatedAt: Date.now() - 432000000,
    },
    {
        id: 'news-6',
        title: 'Djokovic, Indian Wells\'te Alcaraz\'ı Devirerek Şampiyon Oldu',
        slug: 'djokovic-indian-wells-alcaraz-sampiyon',
        excerpt: 'Sırp tenisçi, finalde Alcaraz\'ı 3 sette geçerek 98. ATP şampiyonluğuna ulaştı.',
        content: '<h2>Efsane Durmak Bilmiyor</h2><p>Novak Djokovic, Indian Wells Masters 1000 finalinde Carlos Alcaraz\'ı 7-5, 4-6, 6-3 skoruyla mağlup ederek turnuvanın şampiyonu oldu.</p><p>37 yaşındaki Sırp tenisçi, kariyerinin 98. ATP zaferine ulaşırken, genç rakibi Alcaraz\'a nesiller arası bir ders verdi.</p><h2>Sıradaki Hedef</h2><p>Djokovic, 100. zafer barajını Miami Open\'da kırmayı hedefliyor.</p>',
        category: 'Tenis',
        image: 'https://picsum.photos/seed/tennis-dj/800/450',
        authorId: 'author-1',
        authorName: 'Spor Editörü',
        views: 934,
        status: 'published',
        createdAt: Date.now() - 518400000,
        updatedAt: Date.now() - 518400000,
    },
    {
        id: 'news-7',
        title: 'Beşiktaş-Galatasaray Derbisi: Taktik Savaş Bekleniyor',
        slug: 'besiktas-galatasaray-derbisi-taktik',
        excerpt: 'Süper Lig\'in en ateşli derbisinde iki teknik adam arasında taktik satranç oynanacak.',
        content: '<h2>Derbi Ateşi Yanıyor</h2><p>Süper Lig\'in 28. haftasında Beşiktaş ile Galatasaray, Tüpraş Stadyumu\'nda karşı karşıya gelecek.</p><p>Beşiktaş\'ın iç saha performansı bu sezon dikkat çekerken, Galatasaray\'ın deplasman galibiyetleri de göz dolduruyor. İki takımın da savunma disiplinine verdiği önem nedeniyle düşük skorlu bir maç bekleniyor.</p><h2>Kadrolar</h2><p>Her iki takımda da eksik oyuncu bulunmuyor, bu da derbinin kalitesini artıracak.</p>',
        category: 'Futbol',
        image: 'https://picsum.photos/seed/bjk-gs/800/450',
        authorId: 'author-1',
        authorName: 'Spor Editörü',
        views: 2890,
        status: 'published',
        createdAt: Date.now() - 43200000,
        updatedAt: Date.now() - 43200000,
    },
    {
        id: 'news-8',
        title: 'Milano Derbisi: AC Milan ve Inter Arasında Ateşli Gece',
        slug: 'milano-derbisi-ac-milan-inter',
        excerpt: 'Serie A\'nın en büyük derbisinde San Siro\'da gol düellosu bekleniyor.',
        content: '<h2>Derby della Madonnina</h2><p>İtalya futbolunun en ateşli karşılaşması olan Milano Derbisi, bu hafta sonu San Siro\'da oynanacak. AC Milan ve Inter, şampiyonluk yarışında kritik bir virajda.</p><p>Milan\'ın son haftalardaki formu dikkat çekerken, Inter\'in Lautaro Martinez liderliğindeki hücum hattı her maç gol atıyor.</p><h2>İstatistikler</h2><p>Son 10 Milano derbisinin 8\'inde karşılıklı gol çıktı. KG Var seçeneği bu maç için de güçlü duruyor.</p>',
        category: 'Futbol',
        image: 'https://picsum.photos/seed/milan-derby/800/450',
        authorId: 'author-1',
        authorName: 'Spor Editörü',
        views: 1780,
        status: 'published',
        createdAt: Date.now() - 21600000,
        updatedAt: Date.now() - 21600000,
    },
];
