#!/usr/bin/expect -f
set timeout -1
set ip "85.121.178.80"
set password "kQkrGBYHtY76dIF0z1"

spawn scp -o StrictHostKeyChecking=no mgcapi.cjs root@$ip:/opt/724bets-backend/
expect "*?assword:*"
send "$password\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no root@$ip "cd /opt/724bets-backend && node -e \"require('./mgcapi.cjs').updateWebhook().then(() => require('./mgcapi.cjs').getAllGames()).then(console.log);\""
expect "*?assword:*"
send "$password\r"
expect eof
