#!/usr/bin/expect -f

set timeout -1
set ip "85.121.178.80"
set password "kQkrGBYHtY76dIF0z1"

spawn scp -o StrictHostKeyChecking=no socket_server_vps.cjs socket_server.cjs oroplay.cjs mgcapi.cjs gamdom_image_map.json root@$ip:/opt/724bets-backend/
expect "*?assword:*"
send "$password\r"
expect eof

spawn ssh -o StrictHostKeyChecking=no root@$ip "pm2 restart 724bets-api"
expect "*?assword:*"
send "$password\r"
expect eof
